/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class canalStatistics {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected canalStatistics(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(canalStatistics obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      jcanalciJNI.delete_canalStatistics(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setCntReceiveFrames(SWIGTYPE_p__u32 cntReceiveFrames) {
    jcanalciJNI.set_canalStatistics_cntReceiveFrames(swigCPtr, SWIGTYPE_p__u32.getCPtr(cntReceiveFrames));
  }

  public SWIGTYPE_p__u32 getCntReceiveFrames() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_canalStatistics_cntReceiveFrames(swigCPtr), true);
  }

  public void setCntTransmitFrames(SWIGTYPE_p__u32 cntTransmitFrames) {
    jcanalciJNI.set_canalStatistics_cntTransmitFrames(swigCPtr, SWIGTYPE_p__u32.getCPtr(cntTransmitFrames));
  }

  public SWIGTYPE_p__u32 getCntTransmitFrames() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_canalStatistics_cntTransmitFrames(swigCPtr), true);
  }

  public void setCntReceiveData(SWIGTYPE_p__u32 cntReceiveData) {
    jcanalciJNI.set_canalStatistics_cntReceiveData(swigCPtr, SWIGTYPE_p__u32.getCPtr(cntReceiveData));
  }

  public SWIGTYPE_p__u32 getCntReceiveData() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_canalStatistics_cntReceiveData(swigCPtr), true);
  }

  public void setCntTransmitData(SWIGTYPE_p__u32 cntTransmitData) {
    jcanalciJNI.set_canalStatistics_cntTransmitData(swigCPtr, SWIGTYPE_p__u32.getCPtr(cntTransmitData));
  }

  public SWIGTYPE_p__u32 getCntTransmitData() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_canalStatistics_cntTransmitData(swigCPtr), true);
  }

  public void setCntOverruns(SWIGTYPE_p__u32 cntOverruns) {
    jcanalciJNI.set_canalStatistics_cntOverruns(swigCPtr, SWIGTYPE_p__u32.getCPtr(cntOverruns));
  }

  public SWIGTYPE_p__u32 getCntOverruns() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_canalStatistics_cntOverruns(swigCPtr), true);
  }

  public void setCntBusWarnings(SWIGTYPE_p__u32 cntBusWarnings) {
    jcanalciJNI.set_canalStatistics_cntBusWarnings(swigCPtr, SWIGTYPE_p__u32.getCPtr(cntBusWarnings));
  }

  public SWIGTYPE_p__u32 getCntBusWarnings() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_canalStatistics_cntBusWarnings(swigCPtr), true);
  }

  public void setCntBusOff(SWIGTYPE_p__u32 cntBusOff) {
    jcanalciJNI.set_canalStatistics_cntBusOff(swigCPtr, SWIGTYPE_p__u32.getCPtr(cntBusOff));
  }

  public SWIGTYPE_p__u32 getCntBusOff() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_canalStatistics_cntBusOff(swigCPtr), true);
  }

  public canalStatistics() {
    this(jcanalciJNI.new_canalStatistics(), true);
  }

}
