/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface jcanalciConstants {
  public final static int USE_SHM_INTERFACE = jcanalciJNI.get_USE_SHM_INTERFACE();
  public final static int USE_DLL_INTERFACE = jcanalciJNI.get_USE_DLL_INTERFACE();
}
