/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#ifndef SWIG_TEMPLATE_DISAMBIGUATOR
#  if defined(__SUNPRO_CC) 
#    define SWIG_TEMPLATE_DISAMBIGUATOR template
#  else
#    define SWIG_TEMPLATE_DISAMBIGUATOR 
#  endif
#endif


#if defined(__GNUC__)
    typedef long long __int64; /*For gcc on Windows */
#endif
#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "java_cci.h"


#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_java_1cciJNI_cci_1CanalOpen(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
    jint jresult = 0 ;
    char *arg1 = (char *) 0 ;
    unsigned long arg2 ;
    long result;
    
    (void)jenv;
    (void)jcls;
    {
        arg1 = 0;
        if (jarg1) {
            arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
            if (!arg1) return 0;
        }
    }
    arg2 = (unsigned long)jarg2; 
    result = (long)cci_CanalOpen(arg1,arg2);
    
    jresult = (jint)result; 
    {
        if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, arg1); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_java_1cciJNI_cci_1CanalClose(JNIEnv *jenv, jclass jcls, jint jarg1) {
    jint jresult = 0 ;
    long arg1 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (long)jarg1; 
    result = (int)cci_CanalClose(arg1);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_java_1cciJNI_cci_1CanalSend(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
    jint jresult = 0 ;
    long arg1 ;
    canalMsg *arg2 = (canalMsg *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (long)jarg1; 
    arg2 = *(canalMsg **)&jarg2; 
    result = (int)cci_CanalSend(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_java_1cciJNI_cci_1CanalReceive(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
    jint jresult = 0 ;
    long arg1 ;
    canalMsg *arg2 = (canalMsg *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (long)jarg1; 
    arg2 = *(canalMsg **)&jarg2; 
    result = (int)cci_CanalReceive(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_java_1cciJNI_cci_1CanalDataAvailable(JNIEnv *jenv, jclass jcls, jint jarg1) {
    jint jresult = 0 ;
    long arg1 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (long)jarg1; 
    result = (int)cci_CanalDataAvailable(arg1);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_java_1cciJNI_cci_1CanalStatus(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
    jint jresult = 0 ;
    long arg1 ;
    canalStatus *arg2 = (canalStatus *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (long)jarg1; 
    arg2 = *(canalStatus **)&jarg2; 
    result = (int)cci_CanalStatus(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_java_1cciJNI_cci_1CanalStatistics(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
    jint jresult = 0 ;
    long arg1 ;
    canalStatistics *arg2 = (canalStatistics *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (long)jarg1; 
    arg2 = *(canalStatistics **)&jarg2; 
    result = (int)cci_CanalStatistics(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_java_1cciJNI_cci_1CanalFilter(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
    jint jresult = 0 ;
    long arg1 ;
    unsigned long arg2 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (long)jarg1; 
    arg2 = (unsigned long)jarg2; 
    result = (int)cci_CanalFilter(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_java_1cciJNI_cci_1CanalMask(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
    jint jresult = 0 ;
    long arg1 ;
    unsigned long arg2 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (long)jarg1; 
    arg2 = (unsigned long)jarg2; 
    result = (int)cci_CanalMask(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_java_1cciJNI_cci_1CanalBaudrate(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
    jint jresult = 0 ;
    long arg1 ;
    unsigned long arg2 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (long)jarg1; 
    arg2 = (unsigned long)jarg2; 
    result = (int)cci_CanalBaudrate(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_cci_1CanalVersion(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    result = (unsigned long)cci_CanalVersion();
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_cci_1CanalDLLVersion(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    result = (unsigned long)cci_CanalDLLVersion();
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jstring JNICALL Java_java_1cciJNI_cci_1CanalVendorString(JNIEnv *jenv, jclass jcls) {
    jstring jresult = 0 ;
    char *result;
    
    (void)jenv;
    (void)jcls;
    result = (char *)cci_CanalVendorString();
    
    {
        if(result) jresult = (*jenv)->NewStringUTF(jenv, result); 
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_new_1canalMsg(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    canalMsg *result;
    
    (void)jenv;
    (void)jcls;
    result = (canalMsg *)new_canalMsg();
    
    *(canalMsg **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_java_1cciJNI_setCanalMsgId(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    canalMsg *arg1 = (canalMsg *) 0 ;
    unsigned long arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    arg2 = (unsigned long)jarg2; 
    setCanalMsgId(arg1,arg2);
    
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_getCanalMsgId(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalMsg *arg1 = (canalMsg *) 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    result = (unsigned long)getCanalMsgId(arg1);
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_java_1cciJNI_setCanalMsgFlags(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    canalMsg *arg1 = (canalMsg *) 0 ;
    unsigned long arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    arg2 = (unsigned long)jarg2; 
    setCanalMsgFlags(arg1,arg2);
    
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_getCanalMsgFlags(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalMsg *arg1 = (canalMsg *) 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    result = (unsigned long)getCanalMsgFlags(arg1);
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_java_1cciJNI_setCanalMsgExtendedId(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    canalMsg *arg1 = (canalMsg *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    setCanalMsgExtendedId(arg1);
    
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_isCanalMsgExtendedId(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalMsg *arg1 = (canalMsg *) 0 ;
    BOOL result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    result = isCanalMsgExtendedId(arg1);
    
    {
        BOOL * resultptr = (BOOL *) malloc(sizeof(BOOL));
        memmove(resultptr, &result, sizeof(BOOL));
        *(BOOL **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT void JNICALL Java_java_1cciJNI_setCanalMsgStandardId(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    canalMsg *arg1 = (canalMsg *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    setCanalMsgStandardId(arg1);
    
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_isCanalMsgStandardId(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalMsg *arg1 = (canalMsg *) 0 ;
    BOOL result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    result = isCanalMsgStandardId(arg1);
    
    {
        BOOL * resultptr = (BOOL *) malloc(sizeof(BOOL));
        memmove(resultptr, &result, sizeof(BOOL));
        *(BOOL **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT void JNICALL Java_java_1cciJNI_setCanalMsgRemoteFrame(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    canalMsg *arg1 = (canalMsg *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    setCanalMsgRemoteFrame(arg1);
    
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_isCanalMsgRemoteFrame(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalMsg *arg1 = (canalMsg *) 0 ;
    BOOL result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    result = isCanalMsgRemoteFrame(arg1);
    
    {
        BOOL * resultptr = (BOOL *) malloc(sizeof(BOOL));
        memmove(resultptr, &result, sizeof(BOOL));
        *(BOOL **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT void JNICALL Java_java_1cciJNI_setCanalMsgObId(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    canalMsg *arg1 = (canalMsg *) 0 ;
    unsigned long arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    arg2 = (unsigned long)jarg2; 
    setCanalMsgObId(arg1,arg2);
    
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_getCanalObId(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalMsg *arg1 = (canalMsg *) 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    result = (unsigned long)getCanalObId(arg1);
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_java_1cciJNI_setCanalMsgSizeData(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2) {
    canalMsg *arg1 = (canalMsg *) 0 ;
    unsigned char arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    arg2 = (unsigned char)jarg2; 
    setCanalMsgSizeData(arg1,arg2);
    
}


JNIEXPORT jshort JNICALL Java_java_1cciJNI_getCanalMsgSizeData(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jshort jresult = 0 ;
    canalMsg *arg1 = (canalMsg *) 0 ;
    unsigned char result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    result = (unsigned char)getCanalMsgSizeData(arg1);
    
    jresult = (jshort)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_java_1cciJNI_setCanalMsgData(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2, jshort jarg3) {
    canalMsg *arg1 = (canalMsg *) 0 ;
    unsigned char arg2 ;
    unsigned char arg3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    arg2 = (unsigned char)jarg2; 
    arg3 = (unsigned char)jarg3; 
    setCanalMsgData(arg1,arg2,arg3);
    
}


JNIEXPORT jshort JNICALL Java_java_1cciJNI_getCanalMsgData(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2) {
    jshort jresult = 0 ;
    canalMsg *arg1 = (canalMsg *) 0 ;
    unsigned char arg2 ;
    unsigned char result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalMsg **)&jarg1; 
    arg2 = (unsigned char)jarg2; 
    result = (unsigned char)getCanalMsgData(arg1,arg2);
    
    jresult = (jshort)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_new_1canalStatistics(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    PCANALSTATISTICS result;
    
    (void)jenv;
    (void)jcls;
    result = new_canalStatistics();
    
    {
        PCANALSTATISTICS * resultptr = (PCANALSTATISTICS *) malloc(sizeof(PCANALSTATISTICS));
        memmove(resultptr, &result, sizeof(PCANALSTATISTICS));
        *(PCANALSTATISTICS **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_getCanalStatisticsReceiveFrames(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalStatistics *arg1 = (canalStatistics *) 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalStatistics **)&jarg1; 
    result = (unsigned long)getCanalStatisticsReceiveFrames(arg1);
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_getCanalStatisticsTransmitFrames(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalStatistics *arg1 = (canalStatistics *) 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalStatistics **)&jarg1; 
    result = (unsigned long)getCanalStatisticsTransmitFrames(arg1);
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_getCanalStatisticsReceiveData(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalStatistics *arg1 = (canalStatistics *) 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalStatistics **)&jarg1; 
    result = (unsigned long)getCanalStatisticsReceiveData(arg1);
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_getCanalStatisticsTransmitData(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalStatistics *arg1 = (canalStatistics *) 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalStatistics **)&jarg1; 
    result = (unsigned long)getCanalStatisticsTransmitData(arg1);
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_getCanalStatisticsOverruns(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalStatistics *arg1 = (canalStatistics *) 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalStatistics **)&jarg1; 
    result = (unsigned long)getCanalStatisticsOverruns(arg1);
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_getCanalStatisticsBusWarnings(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalStatistics *arg1 = (canalStatistics *) 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalStatistics **)&jarg1; 
    result = (unsigned long)getCanalStatisticsBusWarnings(arg1);
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_getCanalStatisticsBusOff(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalStatistics *arg1 = (canalStatistics *) 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalStatistics **)&jarg1; 
    result = (unsigned long)getCanalStatisticsBusOff(arg1);
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_new_1canalStatus(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    PCANALSTATUS result;
    
    (void)jenv;
    (void)jcls;
    result = new_canalStatus();
    
    {
        PCANALSTATUS * resultptr = (PCANALSTATUS *) malloc(sizeof(PCANALSTATUS));
        memmove(resultptr, &result, sizeof(PCANALSTATUS));
        *(PCANALSTATUS **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_java_1cciJNI_getcanalStatusChannelStatus(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    canalStatus *arg1 = (canalStatus *) 0 ;
    unsigned long result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(canalStatus **)&jarg1; 
    result = (unsigned long)getcanalStatusChannelStatus(arg1);
    
    jresult = (jlong)result; 
    return jresult;
}


#ifdef __cplusplus
}
#endif

