#!/bin/sh
# /etc/init.d/vscpd
#
# Written by Ake Hedman, Grodans Paradis AB <akhe@grodansparadis.com>
### BEGIN INIT INFO
# Provides:          vscpd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: VSCP daemon init. script
# Description:       Init. script for the Very Simple Control Protocol (VSCP) 
# daemon             (vscpd) and should be placed in /etc/init.d
### END INIT INFO


set -e


DAEMON=/usr/local/bin/vscpd
NAME=vscpd

test -x $DAEMON || exit 0
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting VSCP daemon: $NAME"
    [ -d /var/run/vscpd ] || mkdir -p /var/run/vscpd
#    start-stop-daemon --start --background -m --pidfile /var/run/vscpd/vscpd.pid --exec $DAEMON && log_end_msg 0 || log_end_msg 1
     start-stop-daemon --start --pidfile /var/run/vscpd/vscpd.pid --exec $DAEMON && log_end_msg 0 || log_end_msg 1

    ;;
  stop)
    log_begin_msg "Stopping VSCP daemon: $NAME"
     start-stop-daemon --stop --retry 15 --signal 15 --pidfile /var/run/vscpd/vscpd.pid --oknodo --exec $DAEMON && log_end_msg 0 || log_end_msg 1

    ;;
  restart)
    $0 stop
    $0 start
    ;;

  reload|force-reload)
    log_begin_msg "Reloading $NAME configuration files"
    start-stop-daemon --stop --pidfile /var/run/vscpd/vscpd.pid --signal 1 --exec $DAEMON && log_end_msg 0 || log_end_msg 1
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/$NAME {start|stop|restart|reload}"
    exit 1
    ;;
esac

exit 0
