# This file was automatically generated by SWIG
package perl_cci;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package perl_ccic;
bootstrap perl_cci;
package perl_cci;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package perl_cci;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package perl_cci;

*cci_CanalOpen = *perl_ccic::cci_CanalOpen;
*cci_CanalClose = *perl_ccic::cci_CanalClose;
*cci_CanalSend = *perl_ccic::cci_CanalSend;
*cci_CanalReceive = *perl_ccic::cci_CanalReceive;
*cci_CanalDataAvailable = *perl_ccic::cci_CanalDataAvailable;
*cci_CanalStatus = *perl_ccic::cci_CanalStatus;
*cci_CanalStatistics = *perl_ccic::cci_CanalStatistics;
*cci_CanalFilter = *perl_ccic::cci_CanalFilter;
*cci_CanalMask = *perl_ccic::cci_CanalMask;
*cci_CanalBaudrate = *perl_ccic::cci_CanalBaudrate;
*cci_CanalVersion = *perl_ccic::cci_CanalVersion;
*cci_CanalDLLVersion = *perl_ccic::cci_CanalDLLVersion;
*cci_CanalVendorString = *perl_ccic::cci_CanalVendorString;
*new_canalMsg = *perl_ccic::new_canalMsg;
*setCanalMsgId = *perl_ccic::setCanalMsgId;
*getCanalMsgId = *perl_ccic::getCanalMsgId;
*setCanalMsgFlags = *perl_ccic::setCanalMsgFlags;
*getCanalMsgFlags = *perl_ccic::getCanalMsgFlags;
*setCanalMsgExtendedId = *perl_ccic::setCanalMsgExtendedId;
*isCanalMsgExtendedId = *perl_ccic::isCanalMsgExtendedId;
*setCanalMsgStandardId = *perl_ccic::setCanalMsgStandardId;
*isCanalMsgStandardId = *perl_ccic::isCanalMsgStandardId;
*setCanalMsgRemoteFrame = *perl_ccic::setCanalMsgRemoteFrame;
*isCanalMsgRemoteFrame = *perl_ccic::isCanalMsgRemoteFrame;
*setCanalMsgObId = *perl_ccic::setCanalMsgObId;
*getCanalObId = *perl_ccic::getCanalObId;
*setCanalMsgSizeData = *perl_ccic::setCanalMsgSizeData;
*getCanalMsgSizeData = *perl_ccic::getCanalMsgSizeData;
*setCanalMsgData = *perl_ccic::setCanalMsgData;
*getCanalMsgData = *perl_ccic::getCanalMsgData;
*new_canalStatistics = *perl_ccic::new_canalStatistics;
*getCanalStatisticsReceiveFrames = *perl_ccic::getCanalStatisticsReceiveFrames;
*getCanalStatisticsTransmitFrames = *perl_ccic::getCanalStatisticsTransmitFrames;
*getCanalStatisticsReceiveData = *perl_ccic::getCanalStatisticsReceiveData;
*getCanalStatisticsTransmitData = *perl_ccic::getCanalStatisticsTransmitData;
*getCanalStatisticsOverruns = *perl_ccic::getCanalStatisticsOverruns;
*getCanalStatisticsBusWarnings = *perl_ccic::getCanalStatisticsBusWarnings;
*getCanalStatisticsBusOff = *perl_ccic::getCanalStatisticsBusOff;
*new_canalStatus = *perl_ccic::new_canalStatus;
*getcanalStatusChannelStatus = *perl_ccic::getcanalStatusChannelStatus;

# ------- VARIABLE STUBS --------

package perl_cci;

1;
