/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class canalStatus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected canalStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(canalStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      jcanalciJNI.delete_canalStatus(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setChannel_status(SWIGTYPE_p__u32 channel_status) {
    jcanalciJNI.set_canalStatus_channel_status(swigCPtr, SWIGTYPE_p__u32.getCPtr(channel_status));
  }

  public SWIGTYPE_p__u32 getChannel_status() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_canalStatus_channel_status(swigCPtr), true);
  }

  public canalStatus() {
    this(jcanalciJNI.new_canalStatus(), true);
  }

}
