/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class canalMsg {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected canalMsg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(canalMsg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      jcanalciJNI.delete_canalMsg(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setFlags(SWIGTYPE_p__u32 flags) {
    jcanalciJNI.set_canalMsg_flags(swigCPtr, SWIGTYPE_p__u32.getCPtr(flags));
  }

  public SWIGTYPE_p__u32 getFlags() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_canalMsg_flags(swigCPtr), true);
  }

  public void setObid(SWIGTYPE_p__u32 obid) {
    jcanalciJNI.set_canalMsg_obid(swigCPtr, SWIGTYPE_p__u32.getCPtr(obid));
  }

  public SWIGTYPE_p__u32 getObid() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_canalMsg_obid(swigCPtr), true);
  }

  public void setId(SWIGTYPE_p__u32 id) {
    jcanalciJNI.set_canalMsg_id(swigCPtr, SWIGTYPE_p__u32.getCPtr(id));
  }

  public SWIGTYPE_p__u32 getId() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_canalMsg_id(swigCPtr), true);
  }

  public void setSizeData(SWIGTYPE_p__u8 sizeData) {
    jcanalciJNI.set_canalMsg_sizeData(swigCPtr, SWIGTYPE_p__u8.getCPtr(sizeData));
  }

  public SWIGTYPE_p__u8 getSizeData() {
    return new SWIGTYPE_p__u8(jcanalciJNI.get_canalMsg_sizeData(swigCPtr), true);
  }

  public void setData(SWIGTYPE_p__u8 data) {
    jcanalciJNI.set_canalMsg_data(swigCPtr, SWIGTYPE_p__u8.getCPtr(data));
  }

  public SWIGTYPE_p__u8 getData() {
    long cPtr = jcanalciJNI.get_canalMsg_data(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p__u8(cPtr, false);
  }

  public void setTimestamp(SWIGTYPE_p__u32 timestamp) {
    jcanalciJNI.set_canalMsg_timestamp(swigCPtr, SWIGTYPE_p__u32.getCPtr(timestamp));
  }

  public SWIGTYPE_p__u32 getTimestamp() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_canalMsg_timestamp(swigCPtr), true);
  }

  public canalMsg() {
    this(jcanalciJNI.new_canalMsg(), true);
  }

}
