/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CCanalSuperWrapper {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CCanalSuperWrapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CCanalSuperWrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      jcanalciJNI.delete_CCanalSuperWrapper(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CCanalSuperWrapper() {
    this(jcanalciJNI.new_CCanalSuperWrapper__SWIG_0(), true);
  }

  public CCanalSuperWrapper(devItem pItem) {
    this(jcanalciJNI.new_CCanalSuperWrapper__SWIG_1(devItem.getCPtr(pItem)), true);
  }

  public int doCmdOpen(String szInterface, long flags) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdOpen__SWIG_0(swigCPtr, szInterface, flags);
  }

  public int doCmdOpen(String szInterface) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdOpen__SWIG_1(swigCPtr, szInterface);
  }

  public int doCmdOpen() {
    return jcanalciJNI.CCanalSuperWrapper_doCmdOpen__SWIG_2(swigCPtr);
  }

  public boolean doCmdClose() {
    return jcanalciJNI.CCanalSuperWrapper_doCmdClose(swigCPtr);
  }

  public boolean doCmdNOOP() {
    return jcanalciJNI.CCanalSuperWrapper_doCmdNOOP(swigCPtr);
  }

  public boolean doCmdGetLevel(SWIGTYPE_p_unsigned_long plevel) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdGetLevel(swigCPtr, SWIGTYPE_p_unsigned_long.getCPtr(plevel));
  }

  public boolean doCmdSend(canalMsg pMsg) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdSend(swigCPtr, canalMsg.getCPtr(pMsg));
  }

  public boolean doCmdReceive(canalMsg pMsg) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdReceive(swigCPtr, canalMsg.getCPtr(pMsg));
  }

  public int doCmdDataAvailable() {
    return jcanalciJNI.CCanalSuperWrapper_doCmdDataAvailable(swigCPtr);
  }

  public boolean doCmdStatus(canalStatus pStatus) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdStatus(swigCPtr, canalStatus.getCPtr(pStatus));
  }

  public boolean doCmdStatistics(canalStatistics pStatistics) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdStatistics(swigCPtr, canalStatistics.getCPtr(pStatistics));
  }

  public boolean doCmdFilter(long filter) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdFilter(swigCPtr, filter);
  }

  public boolean doCmdMask(long mask) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdMask(swigCPtr, mask);
  }

  public boolean doCmdBaudrate(long baudrate) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdBaudrate(swigCPtr, baudrate);
  }

  public boolean doCmdVersion(SWIGTYPE_p_unsigned_long pversion) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdVersion(swigCPtr, SWIGTYPE_p_unsigned_long.getCPtr(pversion));
  }

  public boolean doCmdDLLVersion(SWIGTYPE_p_unsigned_long pversion) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdDLLVersion(swigCPtr, SWIGTYPE_p_unsigned_long.getCPtr(pversion));
  }

  public boolean doCmdVendorString(String pVendorStr, int maxsize) {
    return jcanalciJNI.CCanalSuperWrapper_doCmdVendorString(swigCPtr, pVendorStr, maxsize);
  }

  public canalMsg new_canalMsg() {
    long cPtr = jcanalciJNI.CCanalSuperWrapper_new_canalMsg(swigCPtr);
    return (cPtr == 0) ? null : new canalMsg(cPtr, false);
  }

  public void setCanalMsgId(canalMsg p, long id) {
    jcanalciJNI.CCanalSuperWrapper_setCanalMsgId(swigCPtr, canalMsg.getCPtr(p), id);
  }

  public long getCanalMsgId(canalMsg p) {
    return jcanalciJNI.CCanalSuperWrapper_getCanalMsgId(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgFlags(canalMsg p, long flags) {
    jcanalciJNI.CCanalSuperWrapper_setCanalMsgFlags(swigCPtr, canalMsg.getCPtr(p), flags);
  }

  public long getCanalMsgFlags(canalMsg p) {
    return jcanalciJNI.CCanalSuperWrapper_getCanalMsgFlags(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgExtendedId(canalMsg p) {
    jcanalciJNI.CCanalSuperWrapper_setCanalMsgExtendedId(swigCPtr, canalMsg.getCPtr(p));
  }

  public boolean isCanalMsgExtendedId(canalMsg p) {
    return jcanalciJNI.CCanalSuperWrapper_isCanalMsgExtendedId(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgStandardId(canalMsg p) {
    jcanalciJNI.CCanalSuperWrapper_setCanalMsgStandardId(swigCPtr, canalMsg.getCPtr(p));
  }

  public boolean isCanalMsgStandardId(canalMsg p) {
    return jcanalciJNI.CCanalSuperWrapper_isCanalMsgStandardId(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgRemoteFrame(canalMsg p) {
    jcanalciJNI.CCanalSuperWrapper_setCanalMsgRemoteFrame(swigCPtr, canalMsg.getCPtr(p));
  }

  public boolean isCanalMsgRemoteFrame(canalMsg p) {
    return jcanalciJNI.CCanalSuperWrapper_isCanalMsgRemoteFrame(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgObId(canalMsg p, long obid) {
    jcanalciJNI.CCanalSuperWrapper_setCanalMsgObId(swigCPtr, canalMsg.getCPtr(p), obid);
  }

  public long getCanalObId(canalMsg p) {
    return jcanalciJNI.CCanalSuperWrapper_getCanalObId(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgSizeData(canalMsg p, int size) {
    jcanalciJNI.CCanalSuperWrapper_setCanalMsgSizeData(swigCPtr, canalMsg.getCPtr(p), size);
  }

  public int getCanalMsgSizeData(canalMsg p) {
    return jcanalciJNI.CCanalSuperWrapper_getCanalMsgSizeData(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgData(canalMsg p, int pos, int data) {
    jcanalciJNI.CCanalSuperWrapper_setCanalMsgData(swigCPtr, canalMsg.getCPtr(p), pos, data);
  }

  public int getCanalMsgData(canalMsg p, int pos) {
    return jcanalciJNI.CCanalSuperWrapper_getCanalMsgData(swigCPtr, canalMsg.getCPtr(p), pos);
  }

  public SWIGTYPE_p_PCANALSTATISTICS new_canalStatistics() {
    return new SWIGTYPE_p_PCANALSTATISTICS(jcanalciJNI.CCanalSuperWrapper_new_canalStatistics(swigCPtr), true);
  }

  public long getCanalStatisticsReceiveFrames(canalStatistics p) {
    return jcanalciJNI.CCanalSuperWrapper_getCanalStatisticsReceiveFrames(swigCPtr, canalStatistics.getCPtr(p));
  }

  public long getCanalStatisticsTransmitFrames(canalStatistics p) {
    return jcanalciJNI.CCanalSuperWrapper_getCanalStatisticsTransmitFrames(swigCPtr, canalStatistics.getCPtr(p));
  }

  public long getCanalStatisticsReceiveData(canalStatistics p) {
    return jcanalciJNI.CCanalSuperWrapper_getCanalStatisticsReceiveData(swigCPtr, canalStatistics.getCPtr(p));
  }

  public long getCanalStatisticsTransmitData(canalStatistics p) {
    return jcanalciJNI.CCanalSuperWrapper_getCanalStatisticsTransmitData(swigCPtr, canalStatistics.getCPtr(p));
  }

  public long getCanalStatisticsOverruns(canalStatistics p) {
    return jcanalciJNI.CCanalSuperWrapper_getCanalStatisticsOverruns(swigCPtr, canalStatistics.getCPtr(p));
  }

  public long getCanalStatisticsBusWarnings(canalStatistics p) {
    return jcanalciJNI.CCanalSuperWrapper_getCanalStatisticsBusWarnings(swigCPtr, canalStatistics.getCPtr(p));
  }

  public long getCanalStatisticsBusOff(canalStatistics p) {
    return jcanalciJNI.CCanalSuperWrapper_getCanalStatisticsBusOff(swigCPtr, canalStatistics.getCPtr(p));
  }

  public SWIGTYPE_p_PCANALSTATUS new_canalStatus() {
    return new SWIGTYPE_p_PCANALSTATUS(jcanalciJNI.CCanalSuperWrapper_new_canalStatus(swigCPtr), true);
  }

  public long getcanalStatusChannelStatus(canalStatus p) {
    return jcanalciJNI.CCanalSuperWrapper_getcanalStatusChannelStatus(swigCPtr, canalStatus.getCPtr(p));
  }

  public devItem new_devItem() {
    long cPtr = jcanalciJNI.CCanalSuperWrapper_new_devItem(swigCPtr);
    return (cPtr == 0) ? null : new devItem(cPtr, false);
  }

  public void setdevItemId(devItem p, int id) {
    jcanalciJNI.CCanalSuperWrapper_setdevItemId(swigCPtr, devItem.getCPtr(p), id);
  }

  public int getdevItemId(devItem p) {
    return jcanalciJNI.CCanalSuperWrapper_getdevItemId(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemRegId(devItem p, int id) {
    jcanalciJNI.CCanalSuperWrapper_setdevItemRegId(swigCPtr, devItem.getCPtr(p), id);
  }

  public int getdevItemRegId(devItem p) {
    return jcanalciJNI.CCanalSuperWrapper_getdevItemRegId(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemName(devItem p, String pname) {
    jcanalciJNI.CCanalSuperWrapper_setdevItemName(swigCPtr, devItem.getCPtr(p), pname);
  }

  public String getdevItemName(devItem p) {
    return jcanalciJNI.CCanalSuperWrapper_getdevItemName(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemPath(devItem p, String pdeviceStr) {
    jcanalciJNI.CCanalSuperWrapper_setdevItemPath(swigCPtr, devItem.getCPtr(p), pdeviceStr);
  }

  public String getdevItemPath(devItem p) {
    return jcanalciJNI.CCanalSuperWrapper_getdevItemPath(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemDeviceString(devItem p, String ppath) {
    jcanalciJNI.CCanalSuperWrapper_setdevItemDeviceString(swigCPtr, devItem.getCPtr(p), ppath);
  }

  public String getdevItemDeviceString(devItem p) {
    return jcanalciJNI.CCanalSuperWrapper_getdevItemDeviceString(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemFlags(devItem p, long flags) {
    jcanalciJNI.CCanalSuperWrapper_setdevItemFlags(swigCPtr, devItem.getCPtr(p), flags);
  }

  public long getdevItemFlags(devItem p) {
    return jcanalciJNI.CCanalSuperWrapper_getdevItemFlags(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemInBufSize(devItem p, long inbufsize) {
    jcanalciJNI.CCanalSuperWrapper_setdevItemInBufSize(swigCPtr, devItem.getCPtr(p), inbufsize);
  }

  public long getdevItemInBufSize(devItem p) {
    return jcanalciJNI.CCanalSuperWrapper_getdevItemInBufSize(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemOutBufSize(devItem p, long outbufsize) {
    jcanalciJNI.CCanalSuperWrapper_setdevItemOutBufSize(swigCPtr, devItem.getCPtr(p), outbufsize);
  }

  public long getdevItemOutBufSize(devItem p) {
    return jcanalciJNI.CCanalSuperWrapper_getdevItemOutBufSize(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemFilter(devItem p, long filter) {
    jcanalciJNI.CCanalSuperWrapper_setdevItemFilter(swigCPtr, devItem.getCPtr(p), filter);
  }

  public long getdevItemFilter(devItem p) {
    return jcanalciJNI.CCanalSuperWrapper_getdevItemFilter(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemMask(devItem p, long mask) {
    jcanalciJNI.CCanalSuperWrapper_setdevItemMask(swigCPtr, devItem.getCPtr(p), mask);
  }

  public long getdevItemMask(devItem p) {
    return jcanalciJNI.CCanalSuperWrapper_getdevItemMask(swigCPtr, devItem.getCPtr(p));
  }

}
