/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class devItem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected devItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(devItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      jcanalciJNI.delete_devItem(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setId(int id) {
    jcanalciJNI.set_devItem_id(swigCPtr, id);
  }

  public int getId() {
    return jcanalciJNI.get_devItem_id(swigCPtr);
  }

  public void setRegid(int regid) {
    jcanalciJNI.set_devItem_regid(swigCPtr, regid);
  }

  public int getRegid() {
    return jcanalciJNI.get_devItem_regid(swigCPtr);
  }

  public void setName(SWIGTYPE_p__u8 name) {
    jcanalciJNI.set_devItem_name(swigCPtr, SWIGTYPE_p__u8.getCPtr(name));
  }

  public SWIGTYPE_p__u8 getName() {
    long cPtr = jcanalciJNI.get_devItem_name(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p__u8(cPtr, false);
  }

  public void setPath(SWIGTYPE_p__u8 path) {
    jcanalciJNI.set_devItem_path(swigCPtr, SWIGTYPE_p__u8.getCPtr(path));
  }

  public SWIGTYPE_p__u8 getPath() {
    long cPtr = jcanalciJNI.get_devItem_path(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p__u8(cPtr, false);
  }

  public void setDeviceStr(SWIGTYPE_p__u8 deviceStr) {
    jcanalciJNI.set_devItem_deviceStr(swigCPtr, SWIGTYPE_p__u8.getCPtr(deviceStr));
  }

  public SWIGTYPE_p__u8 getDeviceStr() {
    long cPtr = jcanalciJNI.get_devItem_deviceStr(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p__u8(cPtr, false);
  }

  public void setFlags(SWIGTYPE_p__u32 flags) {
    jcanalciJNI.set_devItem_flags(swigCPtr, SWIGTYPE_p__u32.getCPtr(flags));
  }

  public SWIGTYPE_p__u32 getFlags() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_devItem_flags(swigCPtr), true);
  }

  public void setInbufsize(SWIGTYPE_p__u32 inbufsize) {
    jcanalciJNI.set_devItem_inbufsize(swigCPtr, SWIGTYPE_p__u32.getCPtr(inbufsize));
  }

  public SWIGTYPE_p__u32 getInbufsize() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_devItem_inbufsize(swigCPtr), true);
  }

  public void setOutbufsize(SWIGTYPE_p__u32 outbufsize) {
    jcanalciJNI.set_devItem_outbufsize(swigCPtr, SWIGTYPE_p__u32.getCPtr(outbufsize));
  }

  public SWIGTYPE_p__u32 getOutbufsize() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_devItem_outbufsize(swigCPtr), true);
  }

  public void setFilter(SWIGTYPE_p__u32 filter) {
    jcanalciJNI.set_devItem_filter(swigCPtr, SWIGTYPE_p__u32.getCPtr(filter));
  }

  public SWIGTYPE_p__u32 getFilter() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_devItem_filter(swigCPtr), true);
  }

  public void setMask(SWIGTYPE_p__u32 mask) {
    jcanalciJNI.set_devItem_mask(swigCPtr, SWIGTYPE_p__u32.getCPtr(mask));
  }

  public SWIGTYPE_p__u32 getMask() {
    return new SWIGTYPE_p__u32(jcanalciJNI.get_devItem_mask(swigCPtr), true);
  }

  public devItem() {
    this(jcanalciJNI.new_devItem(), true);
  }

}
