#!/bin/sh
# postrm script for vscpd
#
# see: dh_installdeb(1)


set -e

case "$1" in
	purge)
		rm -f /var/lib/vscp/vscpd/vscpd.db
		if [ -d /var/lib/vscp/vscpd ]; then
			rmdir --ignore-fail-on-non-empty /var/lib/vscp/vscpd
		fi
		rm -f /var/log/vscp/vscpd.log*
		if [ -d /var/log/vscp ]; then
			rmdir --ignore-fail-on-non-empty /var/log/vscp
		fi
		if [ -d /var/lib/vscp/web ]; then
			rmdir --ignore-fail-on-non-empty /var/lib/vscp/web
		fi
		if [ -d /usr/share/vscp ]; then
			rmdir --ignore-fail-on-non-empty /usr/share/vscp
		fi
        APP_PROFILE="usr.sbin.vscpd"
        rm -f /etc/apparmor.d/disable/$APP_PROFILE >/dev/null 2>&1 || true
	;;
	remove|abort-install|abort-upgrade|disappear)
	;;

	upgrade|failed-upgrade)
	;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask vscpd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge vscpd.service >/dev/null
		deb-systemd-helper unmask vscpd.service >/dev/null
	fi
fi
# End automatically added section

#DEBHELPER#

exit 0