#!/bin/sh
# postinst script for vscpd
#
# see: dh_installdeb(1)

set -e

VSCPD_DEFAULT_FILE=/etc/default/vscp

setup_vscp_config() {
	
    if ! getent passwd vscp >/dev/null; then
        adduser --disabled-password --quiet --system \
                --home /nonexistent --no-create-home --group vscp \
                --shell /bin/false
    fi
    mkdir -p -m 3777 /var/crash
    chmod g+s /var/crash
    chgrp vscp /var/crash
    chgrp vscp /var/crash/*.crash >/dev/null 2>&1 || true
    chmod 0640 /var/crash/*.crash >/dev/null 2>&1 || true

    mkdir -p -m 3777 /var/metrics
    chmod g+s /var/metrics
    chgrp vscp /var/metrics

    if [ -f /etc/vscp ]; then
        # neither report_crashes nor report_metrics is used by vscp
        rm /etc/vscp/vscpd.json
    fi
}

setup_vscpd_user() {
	if ! getent group vscp >/dev/null; then
		addgroup --quiet --system vscp
	fi

	if ! getent passwd vscp >/dev/null; then
		adduser --quiet --system --no-create-home --ingroup vscp --home /var/lib/vscp/vscpd --shell /usr/sbin/nologin vscp vscp
	fi
}

setup_vscpd_systemd() {
  /usr/bin/systemctl enable vscpd.service
  /usr/bin/systemctl start vscpd
}

fix_permissions() {
  chown vscp /var/lib/vscp
  chgrp vscp /var/lib/vscp
  chmod a+x /var/lib/vscp
  chown vscp /var/lib/vscp/drivers
  chgrp vscp /var/lib/vscp/drivers
  chown vscp /var/lib/vscp/drivers/level1
  chgrp vscp /var/lib/vscp/drivers/level1
  chown vscp /var/lib/vscp/drivers/level2
  chgrp vscp /var/lib/vscp/drivers/level2
  chown vscp /var/lib/vscp/vscpd
  chgrp vscp /var/lib/vscp/vscpd
  chown vscp /var/lib/vscp/web
  chgrp vscp /var/lib/vscp/web
  chown vscp /var/lib/vscp/web/html
  chgrp vscp /var/lib/vscp/web/html
  chown vscp /var/lib/vscp/web/html/images
  chgrp vscp /var/lib/vscp/web/html/images
  chown vscp /var/lib/vscp/web/html/css
  chgrp vscp /var/lib/vscp/web/html/css
  chown vscp /var/lib/vscp/web/html/js
  chgrp vscp /var/lib/vscp/web/html/js
  chown vscp /etc/vscp/certs
  chgrp vscp /etc/vscp/certs
  chmod 700 /etc/vscp/certs
  chown vscp /etc/vscp/vscp.key
  chgrp vscp /etc/vscp/vscp.key
  chmod 600 /etc/vscp/vscp.key
  chown vscp /var/log/vscp
  chgrp vscp /var/log/vscp
  chmod 760 var/log/vscp  
}

case "$1" in
	configure)
		setup_vscp_config
		setup_vscpd_user
		fix_permissions
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac



#DEBHELPER#

exit 0
