#!/bin/sh
# postinst script for vscpd
#
# see: dh_installdeb(1)

set -e

VSCPD_DEFAULT_FILE=/etc/default/vscp

setup_vscp_config() {
	
    if ! getent passwd vscp >/dev/null; then
        adduser --disabled-password --quiet --system \
                --home /nonexistent --no-create-home --group vscp \
                --shell /bin/false
    fi
    mkdir -p -m 3777 /var/crash
    chmod g+s /var/crash
    chgrp vscp /var/crash
    chgrp vscp /var/crash/*.crash >/dev/null 2>&1 || true
    chmod 0640 /var/crash/*.crash >/dev/null 2>&1 || true

    mkdir -p -m 3777 /var/metrics
    chmod g+s /var/metrics
    chgrp vscp /var/metrics

    if [ -f /etc/vscp ]; then
        # neither report_crashes nor report_metrics is used by vscp
        rm /etc/vscp/vscpd.json
    fi
}

setup_vscpd_user() {
	if ! getent group vscp >/dev/null; then
		addgroup --quiet --system vscp
	fi

	if ! getent passwd vscp >/dev/null; then
		adduser --quiet --system --no-create-home --ingroup vscp --home /var/lib/vscp/vscpd --shell /usr/sbin/nologin vscp vscp
	fi
}

setup_vscpd_systemd() {
  /usr/bin/systemctl enable vscpd.service
  /usr/bin/systemctl start vscpd
}

fix_permissions() {
  chown vscp /var/lib/vscp
  chgrp vscp /var/lib/vscp
  chmod a+x /var/lib/vscp
  chown vscp /var/lib/vscp/drivers
  chgrp vscp /var/lib/vscp/drivers
  chown vscp /var/lib/vscp/drivers/level1
  chgrp vscp /var/lib/vscp/drivers/level1
  chmod a+x /var/lib/vscp/drivers/level1
  chown vscp /var/lib/vscp/drivers/level2
  chgrp vscp /var/lib/vscp/drivers/level2
  chmod a+x /var/lib/vscp/drivers/level2
  chown vscp /var/lib/vscp/vscpd
  chgrp vscp /var/lib/vscp/vscpd
  chmod a+x /var/lib/vscp/vscpd
  chown vscp /var/lib/vscp/web
  chgrp vscp /var/lib/vscp/web
  chmod a+x /var/lib/vscp/web
  chown vscp /var/lib/vscp/web/html
  chgrp vscp /var/lib/vscp/web/html
  chmod a+x /var/lib/vscp/web/html
  chown vscp /var/lib/vscp/web/html/images
  chgrp vscp /var/lib/vscp/web/html/images
  chmod a+x /var/lib/vscp/web/html/images
  chown vscp /var/lib/vscp/web/html/css
  chgrp vscp /var/lib/vscp/web/html/css
  chmod a+x /var/lib/vscp/web/html/css
  chown vscp /var/lib/vscp/web/html/js
  chgrp vscp /var/lib/vscp/web/html/js
  chmod a+x /var/lib/vscp/web/html/js
  chown vscp /etc/vscp/certs
  chgrp vscp /etc/vscp/certs
  chmod 700 /etc/vscp/certs
  chown vscp /etc/vscp/vscp.key
  chgrp vscp /etc/vscp/vscp.key
  chmod 600 /etc/vscp/vscp.key
  chown vscp /var/log/vscp
  chgrp vscp /var/log/vscp
  chmod 755 var/log/vscp  
}

case "$1" in
	configure)
		setup_vscp_config
		setup_vscpd_user
		fix_permissions
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask vscpd.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled vscpd.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable vscpd.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state vscpd.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	if [ -n "$2" ]; then
		_dh_action=try-restart
	else
		_dh_action=start
	fi
	deb-systemd-invoke $_dh_action vscpd.service >/dev/null || true
fi
# End automatically added section

#DEBHELPER#

exit 0
