#!/bin/sh
# postinst script for vscpd
#
# see: dh_installdeb(1)

set -e

# Stop the vscpd shutdows_vscp_service
setup_vscpd_systemd() {
	/usr/bin/systemctl stop vscpd
}

case "$1" in
	configure)
		shutdows_vscp_service
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
