#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop vscpd.service >/dev/null
fi
# End automatically added section