m4_define([release_debian],  [1])
m4_define([major_version],   [14])
m4_define([minor_version],   [0])
m4_define([release_version], [1])
m4_define([build_version],   [0])
m4_define([package_version],['major_version.minor_version.release_version'])
m4_define([full_version],['major_version.minor_version.release_version.build_version'])