#!/bin/bash
# vscp_eth_to_guid eth0 /etc/vscp/vscpd.json

if [ -f "/usr/bin/sed" ]; then
    echo "sed exists."
    SED=1
fi

IFACE=$1
read MAC < /sys/class/net/$IFACE/address
echo GUID=FF:FF:FF:FF:FF:FF:FF:FE:${MAC^^}:00:00
GUID=FF:FF:FF:FF:FF:FF:FF:FE:${MAC^^}:
if [ -f "$2" ]; then
    echo "$2  exists"
    REGEXP="sed -i 's/FF:FF:FF:FF:FF:FF:FF:F5:00:00:00:00:00:00:/${GUID}/g' $2"
    eval "$REGEXP"
    echo "Fixed GUID in $2"
fi

