/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class java_cci {
  public static int cci_CanalOpen(String pDevice, long flags) {
    return java_cciJNI.cci_CanalOpen(pDevice, flags);
  }

  public static int cci_CanalClose(int handle) {
    return java_cciJNI.cci_CanalClose(handle);
  }

  public static int cci_CanalSend(int handle, SWIGTYPE_p_canalMsg pMsg) {
    return java_cciJNI.cci_CanalSend(handle, SWIGTYPE_p_canalMsg.getCPtr(pMsg));
  }

  public static int cci_CanalReceive(int handle, SWIGTYPE_p_canalMsg pMsg) {
    return java_cciJNI.cci_CanalReceive(handle, SWIGTYPE_p_canalMsg.getCPtr(pMsg));
  }

  public static int cci_CanalDataAvailable(int handle) {
    return java_cciJNI.cci_CanalDataAvailable(handle);
  }

  public static int cci_CanalStatus(int handle, SWIGTYPE_p_canalStatus pStatus) {
    return java_cciJNI.cci_CanalStatus(handle, SWIGTYPE_p_canalStatus.getCPtr(pStatus));
  }

  public static int cci_CanalStatistics(int handle, SWIGTYPE_p_canalStatistics pStatistics) {
    return java_cciJNI.cci_CanalStatistics(handle, SWIGTYPE_p_canalStatistics.getCPtr(pStatistics));
  }

  public static int cci_CanalFilter(int handle, long filter) {
    return java_cciJNI.cci_CanalFilter(handle, filter);
  }

  public static int cci_CanalMask(int handle, long mask) {
    return java_cciJNI.cci_CanalMask(handle, mask);
  }

  public static int cci_CanalBaudrate(int handle, long baudrate) {
    return java_cciJNI.cci_CanalBaudrate(handle, baudrate);
  }

  public static long cci_CanalVersion() {
    return java_cciJNI.cci_CanalVersion();
  }

  public static long cci_CanalDLLVersion() {
    return java_cciJNI.cci_CanalDLLVersion();
  }

  public static String cci_CanalVendorString() {
    return java_cciJNI.cci_CanalVendorString();
  }

  public static SWIGTYPE_p_canalMsg new_canalMsg() {
    long cPtr = java_cciJNI.new_canalMsg();
    return (cPtr == 0) ? null : new SWIGTYPE_p_canalMsg(cPtr, false);
  }

  public static void setCanalMsgId(SWIGTYPE_p_canalMsg p, long id) {
    java_cciJNI.setCanalMsgId(SWIGTYPE_p_canalMsg.getCPtr(p), id);
  }

  public static long getCanalMsgId(SWIGTYPE_p_canalMsg p) {
    return java_cciJNI.getCanalMsgId(SWIGTYPE_p_canalMsg.getCPtr(p));
  }

  public static void setCanalMsgFlags(SWIGTYPE_p_canalMsg p, long flags) {
    java_cciJNI.setCanalMsgFlags(SWIGTYPE_p_canalMsg.getCPtr(p), flags);
  }

  public static long getCanalMsgFlags(SWIGTYPE_p_canalMsg p) {
    return java_cciJNI.getCanalMsgFlags(SWIGTYPE_p_canalMsg.getCPtr(p));
  }

  public static void setCanalMsgExtendedId(SWIGTYPE_p_canalMsg p) {
    java_cciJNI.setCanalMsgExtendedId(SWIGTYPE_p_canalMsg.getCPtr(p));
  }

  public static SWIGTYPE_p_BOOL isCanalMsgExtendedId(SWIGTYPE_p_canalMsg p) {
    return new SWIGTYPE_p_BOOL(java_cciJNI.isCanalMsgExtendedId(SWIGTYPE_p_canalMsg.getCPtr(p)), true);
  }

  public static void setCanalMsgStandardId(SWIGTYPE_p_canalMsg p) {
    java_cciJNI.setCanalMsgStandardId(SWIGTYPE_p_canalMsg.getCPtr(p));
  }

  public static SWIGTYPE_p_BOOL isCanalMsgStandardId(SWIGTYPE_p_canalMsg p) {
    return new SWIGTYPE_p_BOOL(java_cciJNI.isCanalMsgStandardId(SWIGTYPE_p_canalMsg.getCPtr(p)), true);
  }

  public static void setCanalMsgRemoteFrame(SWIGTYPE_p_canalMsg p) {
    java_cciJNI.setCanalMsgRemoteFrame(SWIGTYPE_p_canalMsg.getCPtr(p));
  }

  public static SWIGTYPE_p_BOOL isCanalMsgRemoteFrame(SWIGTYPE_p_canalMsg p) {
    return new SWIGTYPE_p_BOOL(java_cciJNI.isCanalMsgRemoteFrame(SWIGTYPE_p_canalMsg.getCPtr(p)), true);
  }

  public static void setCanalMsgObId(SWIGTYPE_p_canalMsg p, long obid) {
    java_cciJNI.setCanalMsgObId(SWIGTYPE_p_canalMsg.getCPtr(p), obid);
  }

  public static long getCanalObId(SWIGTYPE_p_canalMsg p) {
    return java_cciJNI.getCanalObId(SWIGTYPE_p_canalMsg.getCPtr(p));
  }

  public static void setCanalMsgSizeData(SWIGTYPE_p_canalMsg p, short size) {
    java_cciJNI.setCanalMsgSizeData(SWIGTYPE_p_canalMsg.getCPtr(p), size);
  }

  public static short getCanalMsgSizeData(SWIGTYPE_p_canalMsg p) {
    return java_cciJNI.getCanalMsgSizeData(SWIGTYPE_p_canalMsg.getCPtr(p));
  }

  public static void setCanalMsgData(SWIGTYPE_p_canalMsg p, short pos, short data) {
    java_cciJNI.setCanalMsgData(SWIGTYPE_p_canalMsg.getCPtr(p), pos, data);
  }

  public static short getCanalMsgData(SWIGTYPE_p_canalMsg p, short pos) {
    return java_cciJNI.getCanalMsgData(SWIGTYPE_p_canalMsg.getCPtr(p), pos);
  }

  public static SWIGTYPE_p_PCANALSTATISTICS new_canalStatistics() {
    return new SWIGTYPE_p_PCANALSTATISTICS(java_cciJNI.new_canalStatistics(), true);
  }

  public static long getCanalStatisticsReceiveFrames(SWIGTYPE_p_canalStatistics p) {
    return java_cciJNI.getCanalStatisticsReceiveFrames(SWIGTYPE_p_canalStatistics.getCPtr(p));
  }

  public static long getCanalStatisticsTransmitFrames(SWIGTYPE_p_canalStatistics p) {
    return java_cciJNI.getCanalStatisticsTransmitFrames(SWIGTYPE_p_canalStatistics.getCPtr(p));
  }

  public static long getCanalStatisticsReceiveData(SWIGTYPE_p_canalStatistics p) {
    return java_cciJNI.getCanalStatisticsReceiveData(SWIGTYPE_p_canalStatistics.getCPtr(p));
  }

  public static long getCanalStatisticsTransmitData(SWIGTYPE_p_canalStatistics p) {
    return java_cciJNI.getCanalStatisticsTransmitData(SWIGTYPE_p_canalStatistics.getCPtr(p));
  }

  public static long getCanalStatisticsOverruns(SWIGTYPE_p_canalStatistics p) {
    return java_cciJNI.getCanalStatisticsOverruns(SWIGTYPE_p_canalStatistics.getCPtr(p));
  }

  public static long getCanalStatisticsBusWarnings(SWIGTYPE_p_canalStatistics p) {
    return java_cciJNI.getCanalStatisticsBusWarnings(SWIGTYPE_p_canalStatistics.getCPtr(p));
  }

  public static long getCanalStatisticsBusOff(SWIGTYPE_p_canalStatistics p) {
    return java_cciJNI.getCanalStatisticsBusOff(SWIGTYPE_p_canalStatistics.getCPtr(p));
  }

  public static SWIGTYPE_p_PCANALSTATUS new_canalStatus() {
    return new SWIGTYPE_p_PCANALSTATUS(java_cciJNI.new_canalStatus(), true);
  }

  public static long getcanalStatusChannelStatus(SWIGTYPE_p_canalStatus p) {
    return java_cciJNI.getcanalStatusChannelStatus(SWIGTYPE_p_canalStatus.getCPtr(p));
  }

}
