/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class java_cciJNI {
  public final static native int cci_CanalOpen(String jarg1, long jarg2);
  public final static native int cci_CanalClose(int jarg1);
  public final static native int cci_CanalSend(int jarg1, long jarg2);
  public final static native int cci_CanalReceive(int jarg1, long jarg2);
  public final static native int cci_CanalDataAvailable(int jarg1);
  public final static native int cci_CanalStatus(int jarg1, long jarg2);
  public final static native int cci_CanalStatistics(int jarg1, long jarg2);
  public final static native int cci_CanalFilter(int jarg1, long jarg2);
  public final static native int cci_CanalMask(int jarg1, long jarg2);
  public final static native int cci_CanalBaudrate(int jarg1, long jarg2);
  public final static native long cci_CanalVersion();
  public final static native long cci_CanalDLLVersion();
  public final static native String cci_CanalVendorString();
  public final static native long new_canalMsg();
  public final static native void setCanalMsgId(long jarg1, long jarg2);
  public final static native long getCanalMsgId(long jarg1);
  public final static native void setCanalMsgFlags(long jarg1, long jarg2);
  public final static native long getCanalMsgFlags(long jarg1);
  public final static native void setCanalMsgExtendedId(long jarg1);
  public final static native long isCanalMsgExtendedId(long jarg1);
  public final static native void setCanalMsgStandardId(long jarg1);
  public final static native long isCanalMsgStandardId(long jarg1);
  public final static native void setCanalMsgRemoteFrame(long jarg1);
  public final static native long isCanalMsgRemoteFrame(long jarg1);
  public final static native void setCanalMsgObId(long jarg1, long jarg2);
  public final static native long getCanalObId(long jarg1);
  public final static native void setCanalMsgSizeData(long jarg1, short jarg2);
  public final static native short getCanalMsgSizeData(long jarg1);
  public final static native void setCanalMsgData(long jarg1, short jarg2, short jarg3);
  public final static native short getCanalMsgData(long jarg1, short jarg2);
  public final static native long new_canalStatistics();
  public final static native long getCanalStatisticsReceiveFrames(long jarg1);
  public final static native long getCanalStatisticsTransmitFrames(long jarg1);
  public final static native long getCanalStatisticsReceiveData(long jarg1);
  public final static native long getCanalStatisticsTransmitData(long jarg1);
  public final static native long getCanalStatisticsOverruns(long jarg1);
  public final static native long getCanalStatisticsBusWarnings(long jarg1);
  public final static native long getCanalStatisticsBusOff(long jarg1);
  public final static native long new_canalStatus();
  public final static native long getcanalStatusChannelStatus(long jarg1);
}
