/////////////////////////////////////////////////////////////////////////////
// Name:        caninterfaceframe.h
// Purpose:     
// Author:      CanMsgDlg
// Modified by: 
// Created:     20/07/2006 19:19:22
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 20/07/2006 19:19:22

#ifndef _CANINTERFACEFRAME_H_
#define _CANINTERFACEFRAME_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "caninterfaceframe.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/mdi.h"
#include "wx/toolbar.h"
#include "wx/grid.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_FRAME 10000
#define SYMBOL_CANINTERFACEFRAME_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_CANINTERFACEFRAME_TITLE _("VSCP Level I/CAN event window")
#define SYMBOL_CANINTERFACEFRAME_IDNAME ID_FRAME
#define SYMBOL_CANINTERFACEFRAME_SIZE wxSize(400, 300)
#define SYMBOL_CANINTERFACEFRAME_POSITION wxDefaultPosition
#define ID_TOOLBAR1 10002
#define ID_PANEL1 10003
#define ID_GRID1 10004
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * CANInterfaceFrame class declaration
 */

class CANInterfaceFrame: public wxMDIChildFrame
{    
    DECLARE_CLASS( CANInterfaceFrame )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CANInterfaceFrame( );
    CANInterfaceFrame( wxMDIParentFrame* parent, wxWindowID id = SYMBOL_CANINTERFACEFRAME_IDNAME, const wxString& caption = SYMBOL_CANINTERFACEFRAME_TITLE, const wxPoint& pos = SYMBOL_CANINTERFACEFRAME_POSITION, const wxSize& size = SYMBOL_CANINTERFACEFRAME_SIZE, long style = SYMBOL_CANINTERFACEFRAME_STYLE );

    bool Create( wxMDIParentFrame* parent, wxWindowID id = SYMBOL_CANINTERFACEFRAME_IDNAME, const wxString& caption = SYMBOL_CANINTERFACEFRAME_TITLE, const wxPoint& pos = SYMBOL_CANINTERFACEFRAME_POSITION, const wxSize& size = SYMBOL_CANINTERFACEFRAME_SIZE, long style = SYMBOL_CANINTERFACEFRAME_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin CANInterfaceFrame event handler declarations

////@end CANInterfaceFrame event handler declarations

////@begin CANInterfaceFrame member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CANInterfaceFrame member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin CANInterfaceFrame member variables
////@end CANInterfaceFrame member variables
};

#endif
    // _CANINTERFACEFRAME_H_
