/////////////////////////////////////////////////////////////////////////////
// Name:        caninterfaceframe.cpp
// Purpose:     
// Author:      CanMsgDlg
// Modified by: 
// Created:     20/07/2006 19:19:22
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 20/07/2006 19:19:22

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "caninterfaceframe.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "caninterfaceframe.h"

////@begin XPM images
////@end XPM images

/*!
 * CANInterfaceFrame type definition
 */

IMPLEMENT_CLASS( CANInterfaceFrame, wxMDIChildFrame )

/*!
 * CANInterfaceFrame event table definition
 */

BEGIN_EVENT_TABLE( CANInterfaceFrame, wxMDIChildFrame )

////@begin CANInterfaceFrame event table entries
////@end CANInterfaceFrame event table entries

END_EVENT_TABLE()

/*!
 * CANInterfaceFrame constructors
 */

CANInterfaceFrame::CANInterfaceFrame( )
{
}

CANInterfaceFrame::CANInterfaceFrame( wxMDIParentFrame* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Create( parent, id, caption, pos, size, style );
}

/*!
 * CANInterfaceFrame creator
 */

bool CANInterfaceFrame::Create( wxMDIParentFrame* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin CANInterfaceFrame member initialisation
////@end CANInterfaceFrame member initialisation

////@begin CANInterfaceFrame creation
    wxMDIChildFrame::Create( parent, id, caption, pos, size, style );

    CreateControls();
    Centre();
////@end CANInterfaceFrame creation
    return true;
}

/*!
 * Control creation for CANInterfaceFrame
 */

void CANInterfaceFrame::CreateControls()
{    
////@begin CANInterfaceFrame content construction
    // Generated by DialogBlocks, 20/07/2006 19:38:32 (unregistered)

    CANInterfaceFrame* itemMDIChildFrame1 = this;

    wxToolBar* itemToolBar2 = CreateToolBar( wxTB_FLAT|wxTB_HORIZONTAL, ID_TOOLBAR1 );
    itemToolBar2->Realize();
    itemMDIChildFrame1->SetToolBar(itemToolBar2);

    wxPanel* itemPanel3 = new wxPanel( itemMDIChildFrame1, ID_PANEL1, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );

    wxGrid* itemGrid4 = new wxGrid( itemPanel3, ID_GRID1, wxDefaultPosition, wxSize(100, 150), wxSUNKEN_BORDER|wxHSCROLL|wxVSCROLL );
    itemGrid4->SetDefaultColSize(50);
    itemGrid4->SetDefaultRowSize(25);
    itemGrid4->SetColLabelSize(25);
    itemGrid4->SetRowLabelSize(50);
    itemGrid4->CreateGrid(5, 5, wxGrid::wxGridSelectCells);

////@end CANInterfaceFrame content construction
}

/*!
 * Should we show tooltips?
 */

bool CANInterfaceFrame::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap CANInterfaceFrame::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin CANInterfaceFrame bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end CANInterfaceFrame bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon CANInterfaceFrame::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin CANInterfaceFrame icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end CANInterfaceFrame icon retrieval
}
