/////////////////////////////////////////////////////////////////////////////
// Name:        ts.cpp
// Purpose:     
// Author:      CanMsgDlg
// Modified by: 
// Created:     20/07/2006 22:43:58
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 20/07/2006 22:43:58

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "ts.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "ts.h"

////@begin XPM images

////@end XPM images

/*!
 * ts type definition
 */

IMPLEMENT_CLASS( ts, wxFrame )

/*!
 * ts event table definition
 */

BEGIN_EVENT_TABLE( ts, wxFrame )

////@begin ts event table entries
////@end ts event table entries

END_EVENT_TABLE()

/*!
 * ts constructors
 */

ts::ts( )
{
}

ts::ts( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Create( parent, id, caption, pos, size, style );
}

/*!
 * ts creator
 */

bool ts::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin ts member initialisation
////@end ts member initialisation

////@begin ts creation
    wxFrame::Create( parent, id, caption, pos, size, style );

    CreateControls();
    Centre();
////@end ts creation
    return true;
}

/*!
 * Control creation for ts
 */

void ts::CreateControls()
{    
////@begin ts content construction
    // Generated by DialogBlocks, 20/07/2006 22:43:58 (unregistered)

    ts* itemFrame1 = this;

////@end ts content construction
}

/*!
 * Should we show tooltips?
 */

bool ts::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap ts::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin ts bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end ts bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon ts::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin ts icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end ts icon retrieval
}
