/////////////////////////////////////////////////////////////////////////////
// Name:        ts.h
// Purpose:     
// Author:      CanMsgDlg
// Modified by: 
// Created:     20/07/2006 22:43:58
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 20/07/2006 22:43:58

#ifndef _TS_H_
#define _TS_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "ts.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/frame.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_FRAME 10000
#define SYMBOL_TS_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_TS_TITLE _("ts")
#define SYMBOL_TS_IDNAME ID_FRAME
#define SYMBOL_TS_SIZE wxSize(400, 300)
#define SYMBOL_TS_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * ts class declaration
 */

class ts: public wxFrame
{    
    DECLARE_CLASS( ts )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ts( );
    ts( wxWindow* parent, wxWindowID id = SYMBOL_TS_IDNAME, const wxString& caption = SYMBOL_TS_TITLE, const wxPoint& pos = SYMBOL_TS_POSITION, const wxSize& size = SYMBOL_TS_SIZE, long style = SYMBOL_TS_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_TS_IDNAME, const wxString& caption = SYMBOL_TS_TITLE, const wxPoint& pos = SYMBOL_TS_POSITION, const wxSize& size = SYMBOL_TS_SIZE, long style = SYMBOL_TS_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin ts event handler declarations
////@end ts event handler declarations

////@begin ts member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ts member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ts member variables
////@end ts member variables
};

#endif
    // _TS_H_
