/////////////////////////////////////////////////////////////////////////////
// Name:        vscpdaemoninterface.cpp
// Purpose:     
// Author:      CanMsgDlg
// Modified by: 
// Created:     20/07/2006 19:21:05
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 20/07/2006 19:21:05

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "vscpdaemoninterface.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "vscpdaemoninterface.h"

////@begin XPM images
////@end XPM images

/*!
 * VSCPDaemonInterface type definition
 */

IMPLEMENT_CLASS( VSCPDaemonInterface, wxMDIChildFrame )

/*!
 * VSCPDaemonInterface event table definition
 */

BEGIN_EVENT_TABLE( VSCPDaemonInterface, wxMDIChildFrame )

////@begin VSCPDaemonInterface event table entries
////@end VSCPDaemonInterface event table entries

END_EVENT_TABLE()

/*!
 * VSCPDaemonInterface constructors
 */

VSCPDaemonInterface::VSCPDaemonInterface( )
{
}

VSCPDaemonInterface::VSCPDaemonInterface( wxMDIParentFrame* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Create( parent, id, caption, pos, size, style );
}

/*!
 * VSCPDaemonInterface creator
 */

bool VSCPDaemonInterface::Create( wxMDIParentFrame* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin VSCPDaemonInterface member initialisation
////@end VSCPDaemonInterface member initialisation

////@begin VSCPDaemonInterface creation
    wxMDIChildFrame::Create( parent, id, caption, pos, size, style );

    CreateControls();
    Centre();
////@end VSCPDaemonInterface creation
    return true;
}

/*!
 * Control creation for VSCPDaemonInterface
 */

void VSCPDaemonInterface::CreateControls()
{    
////@begin VSCPDaemonInterface content construction
    // Generated by DialogBlocks, 20/07/2006 19:22:59 (unregistered)

    VSCPDaemonInterface* itemMDIChildFrame1 = this;

////@end VSCPDaemonInterface content construction
}

/*!
 * Should we show tooltips?
 */

bool VSCPDaemonInterface::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap VSCPDaemonInterface::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin VSCPDaemonInterface bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end VSCPDaemonInterface bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon VSCPDaemonInterface::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin VSCPDaemonInterface icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end VSCPDaemonInterface icon retrieval
}
