#
# Makefile for canald 
#
# Copyright 2004,2005 by Ake Hedman <akhe@eurosource.se>
# See COPYING for GNU Public License
#
# Linux/Solaris/FreeBSD/AIX/Other makefile
#

# * * * Configuration * * *

# topdir for wxWidgets base 
top_builddir = /usr/local/lib
 
#program version
VERSION = 0.1.5

EXTRALIBS = -pthread -lz -ldl -lm
OPENGLLIBS =
LDFLAGS_GL =
LDLIBS = ${APPEXTRALIBS} ${top_builddir}/lib/libwx_based-2.6.a ${EXTRALIBS}

TOOLKIT =
TOOLKITDIR = base

WXLIB = libwx_base-2.6.a
WXSHLIB = libwx_base-2.6.so.0.1.1
WXLIBBASE = wx_base



########################### VERSION #################################

WX_MAJOR_VERSION_NUMBER = 2
WX_MINOR_VERSION_NUMBER = 6
WX_RELEASE_NUMBER = 1

########################### Programs #################################

CXX         = c++
CC          = gcc

# Compiler for lex/yacc .c programs
CCLEX       = gcc

LEX         = flex
YACC        = bison -y
AR          = ar
AS          =
NM          =
LN_S        = ln -s
STRIP       = strip
AROPTIONS   = rcu
RANLIB      = ranlib
LD          =
MAKEINFO    =
RM          = rm -f


########################### Flags #################################

CXXFLAGS = -g -O0 -pthread -I/usr/include/SDL -D_REENTRANT -Wall -Wno-ctor-dtor-privacy
CPPFLAGS = -D__WXDEBUG__  -I${top_builddir}/wx/include/base-ansi-debug-static-2.6  -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D_LARGEFILE_SOURCE=1
CFLAGS = ${APPEXTRACFLAGS} ${CPPFLAGS} -O2 -MMD -pthread -Wall
PICFLAGS =

CANALOBJS = 	../../common/listenthread_unix.o ../../common/clientthread_level1_unix.o ../../common/devicethread_unix.o \
		../../common/canalshmem_level1_unix.o ../../common/clientlist.o ../../common/controlobject.o \
		../../common/devicelist.o ../../common/udpreceivethread_unix.o ../../../vscp/common/vscp.o \
		../../common/clientthread_level2_unix.o ../../common/canalshmem_level2_unix.o \
		../../common/tcplistenthread.o
CANALHDRS =	../../common/clientlist.h ../../common/controlobject.h ../../common/devicelist.h \
		../../common/canal.h ../../common/canaldlldef.h \
		../../common/version.h ../../common/canal_unix_ipc.h ../../common/CanalShMem_level1_unix.h \
		../../common/CanalShMem_level2_unix.h ../../common/clientthread_level1_unix.h ../../common/clientthread_level2_unix.h
PROJOBJS	= ../../../common/dllist.o ../../../common/configfile.o ../../../common/crc.o
PROJHDRS	= ../../../common/dllist.h ../../../common/configfile.h
OBJS		= canald.o
HDRS		= canald.h


# !!!!!!!
# To enable Linux support uncomment the following line (default)
# !!!!!!!
CFLAGS	+= -DLINUX

# !!!!!!!
# To enable Solaris support uncomment the following line
# This does not yet work in v2.0, anyone with Solaris want to port it??
# !!!!!!!
#CFLAGS	+= -DSOLARIS
#LIBS += -lposix4

# !!!!!!!
# To enable AIX support uncomment the following line
# !!!!!!!
#CFLAGS += -DAIX

# !!!!!!!
# To enable FreeBSD support uncomment the following line
# !!!!!!!
#CFLAGS += -DFREEBSD
  
# !!!!!!!
# If you don't use one of the above, uncomment this line and much with
# the settings in src/digitemp.c and send back your changes.
# !!!!!!!
#CFLAGS += -DOTHER


all:		canald

# Build the Linux executable
canald:		$(OBJS) $(HDRS) $(CANALOBJS) $(CANALHDR) $(PROJOBJS) $(PROJHDRS)
		$(CXX) $(OBJS) $(CANALOBJS) $(PROJOBJS) -o canald $(LIBS) $(LDLIBS)

# Clean up the object files and the sub-directory for distributions
clean:
		rm -f *~ $(OBJS) $(CANALOBJS) $(PROJOBJS) core *.asc 
		rm -f perl/*~ rrdb/*~ .canalrc canal-$(VERSION)-1.spec
		rm -rf canal-$(VERSION)

# Sign the binaries using gpg (www.gnupg.org)
# My key is available from www.vscp.org
sign:
		gpg -ba canald


# Install canald into /usr/local/bin
install:	canald
		install -b -o root -g bin canald /usr/local/bin

# Build the archive of everything
archive:	canald clean sign
		cd .. ; tar cvzf ../../delivery/canald-$(VERSION).tar.gz * --exclude *.o --exclude *.exe 

# Build the source distribution

source:		archive

dist:		archive

# Build RedHat binary and source RPMs
rpm:	dist
	su -c "cp ../../delivery/canald-$(VERSION).tar.gz /usr/src/redhat/SOURCES"
	rm -f canald-$(VERSION)-1.spec
	ln -s canald.spec canald-$(VERSION)-1.spec
	su -c "rpm -ba -vv canald-$(VERSION)-1.spec"

