#!/bin/bash
#
# This script is run after installation of a debian package
#
#

VSCP_PROJ_BASE_DIR="/srv/vscp"
INSTALL_PROGRAM="/usr/bin/install -c"

# startup script
if [ ! -e /etc/init.d/vscpd ]; then
    $INSTALL_PROGRAM -b -m755 $VSCP_PROJ_BASE_DIR/tmp/vscpd.startup_script_debian_debinst /etc/init.d/vscpd
    update-rc.d vscpd defaults
fi

# main configuration file
if [ ! -e /etc/vscp/vscpd.conf ]; then
    $INSTALL_PROGRAM -b -m744 $VSCP_PROJ_BASE_DIR/tmp/vscpd.conf_unix_distro /etc/vscp/vscpd.conf
else
    $INSTALL_PROGRAM -b -m744 $VSCP_PROJ_BASE_DIR/tmp/vscpd.conf_unix_distro /etc/vscp/vscpd.conf.`date +'%Y%m%d'`
fi

# Example variables
if [ ! -e /etc/vscp/variables.xml ]; then
    $INSTALL_PROGRAM -b -m744 $VSCP_PROJ_BASE_DIR/tmp/variables.xml_distro $VSCP_PROJ_BASE_DIR/variables.xml
else
    $INSTALL_PROGRAM -b -m744 $VSCP_PROJ_BASE_DIR/tmp/variables.xml_distro $VSCP_PROJ_BASE_DIR/variables.xml.`date +'%Y%m%d'`
fi

# Example DM
if [ ! -e /etc/vscp/dm.xml ]; then
    $INSTALL_PROGRAM -b -m744 $VSCP_PROJ_BASE_DIR/tmp/dm.xml_distro $VSCP_PROJ_BASE_DIR/dm.xml
else
    $INSTALL_PROGRAM -b -m744 $VSCP_PROJ_BASE_DIR/tmp/dm.xml_distro $VSCP_PROJ_BASE_DIR/dm.xml.`date +'%Y%m%d'`
fi

# Sample data for simulation
if [ ! -e /etc/vscp/simtempdata.txt ]; then
    $INSTALL_PROGRAM -b -m744 $VSCP_PROJ_BASE_DIR/tmp/simtempdata.txt $VSCP_PROJ_BASE_DIR/simtempdata.txt
else
    $INSTALL_PROGRAM -b -m744 $VSCP_PROJ_BASE_DIR/tmp/simtempdata.txt $VSCP_PROJ_BASE_DIR/simtempdata.txt.`date +'%Y%m%d'`
fi

# Server sample certificat
if [ ! -e /etc/vscp/certs/server.pem ]; then
    $INSTALL_PROGRAM -b -m744 $VSCP_PROJ_BASE_DIR/tmp/server.pem $VSCP_PROJ_BASE_DIR/certs
fi

# Client sample certificat
if [ ! -e /etc/vscp/certs/client.pem ]; then
    $INSTALL_PROGRAM -b -m744 $VSCP_PROJ_BASE_DIR/tmp/client.pem $VSCP_PROJ_BASE_DIR/certs
fi


# Remove the temporary file folder
rm -rf /srv/tmp

# Start the VSCP server
/etc/init.d/vscpd start
