#!/bin/bash
#
# This script is run before installation of a debian package
#
#

VSCP_PROJ_BASE_DIR="/srv/vscp"
INSTALL_PROGRAM="/usr/bin/install -c"

# Stop VSCP server (in case of update operation)
if [ -e /var/run/vscpd/vscpd.pid ]; then
   /etc/init.d/vscpd stop
fi

# create folder structure
mkdir -p $VSCP_PROJ_BASE_DIR
mkdir -p $VSCP_PROJ_BASE_DIR/tmp
mkdir -p $VSCP_PROJ_BASE_DIR/logs
mkdir -p $VSCP_PROJ_BASE_DIR/actions
mkdir -p $VSCP_PROJ_BASE_DIR/scripts
mkdir -p $VSCP_PROJ_BASE_DIR/scripts/javascript
mkdir -p $VSCP_PROJ_BASE_DIR/scripts/lua
mkdir -p $VSCP_PROJ_BASE_DIR/ux
mkdir -p $VSCP_PROJ_BASE_DIR/web
mkdir -p $VSCP_PROJ_BASE_DIR/certs
mkdir -p $VSCP_PROJ_BASE_DIR/drivers
mkdir -p $VSCP_PROJ_BASE_DIR/drivers/level1
mkdir -p $VSCP_PROJ_BASE_DIR/drivers/level2
mkdir -p $VSCP_PROJ_BASE_DIR/upload
mkdir -p $VSCP_PROJ_BASE_DIR/web/css
mkdir -p $VSCP_PROJ_BASE_DIR/web/images
mkdir -p $VSCP_PROJ_BASE_DIR/web/lib
mkdir -p $VSCP_PROJ_BASE_DIR/web/testws
mkdir -p $VSCP_PROJ_BASE_DIR/vscp
mkdir -p $VSCP_PROJ_BASE_DIR/tables
mkdir -p $VSCP_PROJ_BASE_DIR/mdf
mkdir -p /etc/vscp
