/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class CCanalSuperWrapper : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal CCanalSuperWrapper(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(CCanalSuperWrapper obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~CCanalSuperWrapper() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      cscanalciPINVOKE.delete_CCanalSuperWrapper(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public CCanalSuperWrapper() : this(cscanalciPINVOKE.new_CCanalSuperWrapper__SWIG_0(), true) {
  }

  public CCanalSuperWrapper(devItem pItem) : this(cscanalciPINVOKE.new_CCanalSuperWrapper__SWIG_1(devItem.getCPtr(pItem)), true) {
  }

  public int doCmdOpen(string szInterface, uint flags) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdOpen__SWIG_0(swigCPtr, szInterface, flags);
  }

  public int doCmdOpen(string szInterface) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdOpen__SWIG_1(swigCPtr, szInterface);
  }

  public int doCmdOpen() {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdOpen__SWIG_2(swigCPtr);
  }

  public bool doCmdClose() {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdClose(swigCPtr);
  }

  public bool doCmdNOOP() {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdNOOP(swigCPtr);
  }

  public bool doCmdGetLevel(SWIGTYPE_p_unsigned_long plevel) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdGetLevel(swigCPtr, SWIGTYPE_p_unsigned_long.getCPtr(plevel));
  }

  public bool doCmdSend(canalMsg pMsg) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdSend(swigCPtr, canalMsg.getCPtr(pMsg));
  }

  public bool doCmdReceive(canalMsg pMsg) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdReceive(swigCPtr, canalMsg.getCPtr(pMsg));
  }

  public int doCmdDataAvailable() {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdDataAvailable(swigCPtr);
  }

  public bool doCmdStatus(canalStatus pStatus) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdStatus(swigCPtr, canalStatus.getCPtr(pStatus));
  }

  public bool doCmdStatistics(canalStatistics pStatistics) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdStatistics(swigCPtr, canalStatistics.getCPtr(pStatistics));
  }

  public bool doCmdFilter(uint filter) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdFilter(swigCPtr, filter);
  }

  public bool doCmdMask(uint mask) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdMask(swigCPtr, mask);
  }

  public bool doCmdBaudrate(uint baudrate) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdBaudrate(swigCPtr, baudrate);
  }

  public bool doCmdVersion(SWIGTYPE_p_unsigned_long pversion) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdVersion(swigCPtr, SWIGTYPE_p_unsigned_long.getCPtr(pversion));
  }

  public bool doCmdDLLVersion(SWIGTYPE_p_unsigned_long pversion) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdDLLVersion(swigCPtr, SWIGTYPE_p_unsigned_long.getCPtr(pversion));
  }

  public bool doCmdVendorString(string pVendorStr, ushort maxsize) {
    return cscanalciPINVOKE.CCanalSuperWrapper_doCmdVendorString(swigCPtr, pVendorStr, maxsize);
  }

  public canalMsg new_canalMsg() {
    IntPtr cPtr = cscanalciPINVOKE.CCanalSuperWrapper_new_canalMsg(swigCPtr);
    return (cPtr == IntPtr.Zero) ? null : new canalMsg(cPtr, false);
  }

  public void setCanalMsgId(canalMsg p, uint id) {
    cscanalciPINVOKE.CCanalSuperWrapper_setCanalMsgId(swigCPtr, canalMsg.getCPtr(p), id);
  }

  public uint getCanalMsgId(canalMsg p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getCanalMsgId(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgFlags(canalMsg p, uint flags) {
    cscanalciPINVOKE.CCanalSuperWrapper_setCanalMsgFlags(swigCPtr, canalMsg.getCPtr(p), flags);
  }

  public uint getCanalMsgFlags(canalMsg p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getCanalMsgFlags(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgExtendedId(canalMsg p) {
    cscanalciPINVOKE.CCanalSuperWrapper_setCanalMsgExtendedId(swigCPtr, canalMsg.getCPtr(p));
  }

  public bool isCanalMsgExtendedId(canalMsg p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_isCanalMsgExtendedId(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgStandardId(canalMsg p) {
    cscanalciPINVOKE.CCanalSuperWrapper_setCanalMsgStandardId(swigCPtr, canalMsg.getCPtr(p));
  }

  public bool isCanalMsgStandardId(canalMsg p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_isCanalMsgStandardId(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgRemoteFrame(canalMsg p) {
    cscanalciPINVOKE.CCanalSuperWrapper_setCanalMsgRemoteFrame(swigCPtr, canalMsg.getCPtr(p));
  }

  public bool isCanalMsgRemoteFrame(canalMsg p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_isCanalMsgRemoteFrame(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgObId(canalMsg p, uint obid) {
    cscanalciPINVOKE.CCanalSuperWrapper_setCanalMsgObId(swigCPtr, canalMsg.getCPtr(p), obid);
  }

  public uint getCanalObId(canalMsg p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getCanalObId(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgSizeData(canalMsg p, int size) {
    cscanalciPINVOKE.CCanalSuperWrapper_setCanalMsgSizeData(swigCPtr, canalMsg.getCPtr(p), size);
  }

  public int getCanalMsgSizeData(canalMsg p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getCanalMsgSizeData(swigCPtr, canalMsg.getCPtr(p));
  }

  public void setCanalMsgData(canalMsg p, int pos, int data) {
    cscanalciPINVOKE.CCanalSuperWrapper_setCanalMsgData(swigCPtr, canalMsg.getCPtr(p), pos, data);
  }

  public int getCanalMsgData(canalMsg p, int pos) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getCanalMsgData(swigCPtr, canalMsg.getCPtr(p), pos);
  }

  public SWIGTYPE_p_PCANALSTATISTICS new_canalStatistics() {
    return new SWIGTYPE_p_PCANALSTATISTICS(cscanalciPINVOKE.CCanalSuperWrapper_new_canalStatistics(swigCPtr), true);
  }

  public uint getCanalStatisticsReceiveFrames(canalStatistics p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getCanalStatisticsReceiveFrames(swigCPtr, canalStatistics.getCPtr(p));
  }

  public uint getCanalStatisticsTransmitFrames(canalStatistics p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getCanalStatisticsTransmitFrames(swigCPtr, canalStatistics.getCPtr(p));
  }

  public uint getCanalStatisticsReceiveData(canalStatistics p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getCanalStatisticsReceiveData(swigCPtr, canalStatistics.getCPtr(p));
  }

  public uint getCanalStatisticsTransmitData(canalStatistics p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getCanalStatisticsTransmitData(swigCPtr, canalStatistics.getCPtr(p));
  }

  public uint getCanalStatisticsOverruns(canalStatistics p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getCanalStatisticsOverruns(swigCPtr, canalStatistics.getCPtr(p));
  }

  public uint getCanalStatisticsBusWarnings(canalStatistics p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getCanalStatisticsBusWarnings(swigCPtr, canalStatistics.getCPtr(p));
  }

  public uint getCanalStatisticsBusOff(canalStatistics p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getCanalStatisticsBusOff(swigCPtr, canalStatistics.getCPtr(p));
  }

  public SWIGTYPE_p_PCANALSTATUS new_canalStatus() {
    return new SWIGTYPE_p_PCANALSTATUS(cscanalciPINVOKE.CCanalSuperWrapper_new_canalStatus(swigCPtr), true);
  }

  public uint getcanalStatusChannelStatus(canalStatus p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getcanalStatusChannelStatus(swigCPtr, canalStatus.getCPtr(p));
  }

  public devItem new_devItem() {
    IntPtr cPtr = cscanalciPINVOKE.CCanalSuperWrapper_new_devItem(swigCPtr);
    return (cPtr == IntPtr.Zero) ? null : new devItem(cPtr, false);
  }

  public void setdevItemId(devItem p, int id) {
    cscanalciPINVOKE.CCanalSuperWrapper_setdevItemId(swigCPtr, devItem.getCPtr(p), id);
  }

  public int getdevItemId(devItem p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getdevItemId(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemRegId(devItem p, int id) {
    cscanalciPINVOKE.CCanalSuperWrapper_setdevItemRegId(swigCPtr, devItem.getCPtr(p), id);
  }

  public int getdevItemRegId(devItem p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getdevItemRegId(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemName(devItem p, string pname) {
    cscanalciPINVOKE.CCanalSuperWrapper_setdevItemName(swigCPtr, devItem.getCPtr(p), pname);
  }

  public string getdevItemName(devItem p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getdevItemName(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemPath(devItem p, string pdeviceStr) {
    cscanalciPINVOKE.CCanalSuperWrapper_setdevItemPath(swigCPtr, devItem.getCPtr(p), pdeviceStr);
  }

  public string getdevItemPath(devItem p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getdevItemPath(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemDeviceString(devItem p, string ppath) {
    cscanalciPINVOKE.CCanalSuperWrapper_setdevItemDeviceString(swigCPtr, devItem.getCPtr(p), ppath);
  }

  public string getdevItemDeviceString(devItem p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getdevItemDeviceString(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemFlags(devItem p, uint flags) {
    cscanalciPINVOKE.CCanalSuperWrapper_setdevItemFlags(swigCPtr, devItem.getCPtr(p), flags);
  }

  public uint getdevItemFlags(devItem p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getdevItemFlags(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemInBufSize(devItem p, uint inbufsize) {
    cscanalciPINVOKE.CCanalSuperWrapper_setdevItemInBufSize(swigCPtr, devItem.getCPtr(p), inbufsize);
  }

  public uint getdevItemInBufSize(devItem p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getdevItemInBufSize(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemOutBufSize(devItem p, uint outbufsize) {
    cscanalciPINVOKE.CCanalSuperWrapper_setdevItemOutBufSize(swigCPtr, devItem.getCPtr(p), outbufsize);
  }

  public uint getdevItemOutBufSize(devItem p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getdevItemOutBufSize(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemFilter(devItem p, uint filter) {
    cscanalciPINVOKE.CCanalSuperWrapper_setdevItemFilter(swigCPtr, devItem.getCPtr(p), filter);
  }

  public uint getdevItemFilter(devItem p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getdevItemFilter(swigCPtr, devItem.getCPtr(p));
  }

  public void setdevItemMask(devItem p, uint mask) {
    cscanalciPINVOKE.CCanalSuperWrapper_setdevItemMask(swigCPtr, devItem.getCPtr(p), mask);
  }

  public uint getdevItemMask(devItem p) {
    return cscanalciPINVOKE.CCanalSuperWrapper_getdevItemMask(swigCPtr, devItem.getCPtr(p));
  }

}
