/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

class cscanalciPINVOKE {

  class SWIGExceptionHelper {

    public delegate void SWIGExceptionDelegate(string message);

    static SWIGExceptionDelegate systemDelegate = new SWIGExceptionDelegate(ThrowSystemException);
    static SWIGExceptionDelegate outOfMemoryDelegate = new SWIGExceptionDelegate(ThrowOutOfMemoryException);
    static SWIGExceptionDelegate indexOutOfRangeDelegate = new SWIGExceptionDelegate(ThrowIndexOutOfRangeException);
    static SWIGExceptionDelegate divideByZeroDelegate = new SWIGExceptionDelegate(ThrowDivideByZeroException);
    static SWIGExceptionDelegate argumentOutOfRangeDelegate = new SWIGExceptionDelegate(ThrowArgumentOutOfRangeException);
    static SWIGExceptionDelegate nullReferenceDelegate = new SWIGExceptionDelegate(ThrowNullReferenceException);

    [DllImport("cscanalci", EntryPoint="SWIGRegisterExceptionCallbacks_cscanalci")]
    public static extern void SWIGRegisterExceptionCallbacks_cscanalci(
      SWIGExceptionDelegate systemExceptionDelegate,
      SWIGExceptionDelegate outOfMemoryDelegate, 
      SWIGExceptionDelegate indexOutOfRangeDelegate, 
      SWIGExceptionDelegate divideByZeroDelegate, 
      SWIGExceptionDelegate argumentOutOfRangeDelegate,
      SWIGExceptionDelegate nullReferenceDelegate);

    static void ThrowSystemException(string message) {
      throw new System.SystemException(message);
    }

    static void ThrowOutOfMemoryException(string message) {
      throw new System.OutOfMemoryException(message);
    }

    static void ThrowIndexOutOfRangeException(string message) {
      throw new System.IndexOutOfRangeException(message);
    }

    static void ThrowDivideByZeroException(string message) {
      throw new System.DivideByZeroException(message);
    }

    static void ThrowArgumentOutOfRangeException(string message) {
      throw new System.ArgumentOutOfRangeException(message);
    }

    static void ThrowNullReferenceException(string message) {
      throw new System.NullReferenceException(message);
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_cscanalci(systemDelegate, outOfMemoryDelegate, indexOutOfRangeDelegate, divideByZeroDelegate, argumentOutOfRangeDelegate, nullReferenceDelegate);
    }
  }

  static SWIGExceptionHelper exceptionHelper = new SWIGExceptionHelper();


  class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("cscanalci", EntryPoint="SWIGRegisterStringCallback_cscanalci")]
    public static extern void SWIGRegisterStringCallback_cscanalci(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_cscanalci(stringDelegate);
    }
  }

  static SWIGStringHelper stringHelper = new SWIGStringHelper();


  [DllImport("cscanalci", EntryPoint="CSharp_get_USE_SHM_INTERFACE")]
  public static extern int get_USE_SHM_INTERFACE();

  [DllImport("cscanalci", EntryPoint="CSharp_get_USE_DLL_INTERFACE")]
  public static extern int get_USE_DLL_INTERFACE();

  [DllImport("cscanalci", EntryPoint="CSharp_new_CCanalSuperWrapper__SWIG_0")]
  public static extern IntPtr new_CCanalSuperWrapper__SWIG_0();

  [DllImport("cscanalci", EntryPoint="CSharp_new_CCanalSuperWrapper__SWIG_1")]
  public static extern IntPtr new_CCanalSuperWrapper__SWIG_1(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_delete_CCanalSuperWrapper")]
  public static extern void delete_CCanalSuperWrapper(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdOpen__SWIG_0")]
  public static extern int CCanalSuperWrapper_doCmdOpen__SWIG_0(IntPtr jarg1, string jarg2, uint jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdOpen__SWIG_1")]
  public static extern int CCanalSuperWrapper_doCmdOpen__SWIG_1(IntPtr jarg1, string jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdOpen__SWIG_2")]
  public static extern int CCanalSuperWrapper_doCmdOpen__SWIG_2(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdClose")]
  public static extern bool CCanalSuperWrapper_doCmdClose(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdNOOP")]
  public static extern bool CCanalSuperWrapper_doCmdNOOP(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdGetLevel")]
  public static extern bool CCanalSuperWrapper_doCmdGetLevel(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdSend")]
  public static extern bool CCanalSuperWrapper_doCmdSend(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdReceive")]
  public static extern bool CCanalSuperWrapper_doCmdReceive(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdDataAvailable")]
  public static extern int CCanalSuperWrapper_doCmdDataAvailable(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdStatus")]
  public static extern bool CCanalSuperWrapper_doCmdStatus(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdStatistics")]
  public static extern bool CCanalSuperWrapper_doCmdStatistics(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdFilter")]
  public static extern bool CCanalSuperWrapper_doCmdFilter(IntPtr jarg1, uint jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdMask")]
  public static extern bool CCanalSuperWrapper_doCmdMask(IntPtr jarg1, uint jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdBaudrate")]
  public static extern bool CCanalSuperWrapper_doCmdBaudrate(IntPtr jarg1, uint jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdVersion")]
  public static extern bool CCanalSuperWrapper_doCmdVersion(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdDLLVersion")]
  public static extern bool CCanalSuperWrapper_doCmdDLLVersion(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_doCmdVendorString")]
  public static extern bool CCanalSuperWrapper_doCmdVendorString(IntPtr jarg1, string jarg2, ushort jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_new_canalMsg")]
  public static extern IntPtr CCanalSuperWrapper_new_canalMsg(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setCanalMsgId")]
  public static extern void CCanalSuperWrapper_setCanalMsgId(IntPtr jarg1, IntPtr jarg2, uint jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getCanalMsgId")]
  public static extern uint CCanalSuperWrapper_getCanalMsgId(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setCanalMsgFlags")]
  public static extern void CCanalSuperWrapper_setCanalMsgFlags(IntPtr jarg1, IntPtr jarg2, uint jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getCanalMsgFlags")]
  public static extern uint CCanalSuperWrapper_getCanalMsgFlags(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setCanalMsgExtendedId")]
  public static extern void CCanalSuperWrapper_setCanalMsgExtendedId(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_isCanalMsgExtendedId")]
  public static extern bool CCanalSuperWrapper_isCanalMsgExtendedId(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setCanalMsgStandardId")]
  public static extern void CCanalSuperWrapper_setCanalMsgStandardId(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_isCanalMsgStandardId")]
  public static extern bool CCanalSuperWrapper_isCanalMsgStandardId(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setCanalMsgRemoteFrame")]
  public static extern void CCanalSuperWrapper_setCanalMsgRemoteFrame(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_isCanalMsgRemoteFrame")]
  public static extern bool CCanalSuperWrapper_isCanalMsgRemoteFrame(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setCanalMsgObId")]
  public static extern void CCanalSuperWrapper_setCanalMsgObId(IntPtr jarg1, IntPtr jarg2, uint jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getCanalObId")]
  public static extern uint CCanalSuperWrapper_getCanalObId(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setCanalMsgSizeData")]
  public static extern void CCanalSuperWrapper_setCanalMsgSizeData(IntPtr jarg1, IntPtr jarg2, int jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getCanalMsgSizeData")]
  public static extern int CCanalSuperWrapper_getCanalMsgSizeData(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setCanalMsgData")]
  public static extern void CCanalSuperWrapper_setCanalMsgData(IntPtr jarg1, IntPtr jarg2, int jarg3, int jarg4);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getCanalMsgData")]
  public static extern int CCanalSuperWrapper_getCanalMsgData(IntPtr jarg1, IntPtr jarg2, int jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_new_canalStatistics")]
  public static extern IntPtr CCanalSuperWrapper_new_canalStatistics(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getCanalStatisticsReceiveFrames")]
  public static extern uint CCanalSuperWrapper_getCanalStatisticsReceiveFrames(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getCanalStatisticsTransmitFrames")]
  public static extern uint CCanalSuperWrapper_getCanalStatisticsTransmitFrames(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getCanalStatisticsReceiveData")]
  public static extern uint CCanalSuperWrapper_getCanalStatisticsReceiveData(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getCanalStatisticsTransmitData")]
  public static extern uint CCanalSuperWrapper_getCanalStatisticsTransmitData(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getCanalStatisticsOverruns")]
  public static extern uint CCanalSuperWrapper_getCanalStatisticsOverruns(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getCanalStatisticsBusWarnings")]
  public static extern uint CCanalSuperWrapper_getCanalStatisticsBusWarnings(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getCanalStatisticsBusOff")]
  public static extern uint CCanalSuperWrapper_getCanalStatisticsBusOff(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_new_canalStatus")]
  public static extern IntPtr CCanalSuperWrapper_new_canalStatus(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getcanalStatusChannelStatus")]
  public static extern uint CCanalSuperWrapper_getcanalStatusChannelStatus(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_new_devItem")]
  public static extern IntPtr CCanalSuperWrapper_new_devItem(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setdevItemId")]
  public static extern void CCanalSuperWrapper_setdevItemId(IntPtr jarg1, IntPtr jarg2, int jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getdevItemId")]
  public static extern int CCanalSuperWrapper_getdevItemId(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setdevItemRegId")]
  public static extern void CCanalSuperWrapper_setdevItemRegId(IntPtr jarg1, IntPtr jarg2, int jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getdevItemRegId")]
  public static extern int CCanalSuperWrapper_getdevItemRegId(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setdevItemName")]
  public static extern void CCanalSuperWrapper_setdevItemName(IntPtr jarg1, IntPtr jarg2, string jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getdevItemName")]
  public static extern string CCanalSuperWrapper_getdevItemName(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setdevItemPath")]
  public static extern void CCanalSuperWrapper_setdevItemPath(IntPtr jarg1, IntPtr jarg2, string jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getdevItemPath")]
  public static extern string CCanalSuperWrapper_getdevItemPath(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setdevItemDeviceString")]
  public static extern void CCanalSuperWrapper_setdevItemDeviceString(IntPtr jarg1, IntPtr jarg2, string jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getdevItemDeviceString")]
  public static extern string CCanalSuperWrapper_getdevItemDeviceString(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setdevItemFlags")]
  public static extern void CCanalSuperWrapper_setdevItemFlags(IntPtr jarg1, IntPtr jarg2, uint jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getdevItemFlags")]
  public static extern uint CCanalSuperWrapper_getdevItemFlags(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setdevItemInBufSize")]
  public static extern void CCanalSuperWrapper_setdevItemInBufSize(IntPtr jarg1, IntPtr jarg2, uint jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getdevItemInBufSize")]
  public static extern uint CCanalSuperWrapper_getdevItemInBufSize(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setdevItemOutBufSize")]
  public static extern void CCanalSuperWrapper_setdevItemOutBufSize(IntPtr jarg1, IntPtr jarg2, uint jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getdevItemOutBufSize")]
  public static extern uint CCanalSuperWrapper_getdevItemOutBufSize(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setdevItemFilter")]
  public static extern void CCanalSuperWrapper_setdevItemFilter(IntPtr jarg1, IntPtr jarg2, uint jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getdevItemFilter")]
  public static extern uint CCanalSuperWrapper_getdevItemFilter(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_setdevItemMask")]
  public static extern void CCanalSuperWrapper_setdevItemMask(IntPtr jarg1, IntPtr jarg2, uint jarg3);

  [DllImport("cscanalci", EntryPoint="CSharp_CCanalSuperWrapper_getdevItemMask")]
  public static extern uint CCanalSuperWrapper_getdevItemMask(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalMsg_flags")]
  public static extern void set_canalMsg_flags(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalMsg_flags")]
  public static extern IntPtr get_canalMsg_flags(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalMsg_obid")]
  public static extern void set_canalMsg_obid(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalMsg_obid")]
  public static extern IntPtr get_canalMsg_obid(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalMsg_id")]
  public static extern void set_canalMsg_id(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalMsg_id")]
  public static extern IntPtr get_canalMsg_id(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalMsg_sizeData")]
  public static extern void set_canalMsg_sizeData(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalMsg_sizeData")]
  public static extern IntPtr get_canalMsg_sizeData(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalMsg_data")]
  public static extern void set_canalMsg_data(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalMsg_data")]
  public static extern IntPtr get_canalMsg_data(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalMsg_timestamp")]
  public static extern void set_canalMsg_timestamp(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalMsg_timestamp")]
  public static extern IntPtr get_canalMsg_timestamp(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_new_canalMsg")]
  public static extern IntPtr new_canalMsg();

  [DllImport("cscanalci", EntryPoint="CSharp_delete_canalMsg")]
  public static extern void delete_canalMsg(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalStatistics_cntReceiveFrames")]
  public static extern void set_canalStatistics_cntReceiveFrames(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalStatistics_cntReceiveFrames")]
  public static extern IntPtr get_canalStatistics_cntReceiveFrames(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalStatistics_cntTransmitFrames")]
  public static extern void set_canalStatistics_cntTransmitFrames(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalStatistics_cntTransmitFrames")]
  public static extern IntPtr get_canalStatistics_cntTransmitFrames(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalStatistics_cntReceiveData")]
  public static extern void set_canalStatistics_cntReceiveData(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalStatistics_cntReceiveData")]
  public static extern IntPtr get_canalStatistics_cntReceiveData(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalStatistics_cntTransmitData")]
  public static extern void set_canalStatistics_cntTransmitData(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalStatistics_cntTransmitData")]
  public static extern IntPtr get_canalStatistics_cntTransmitData(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalStatistics_cntOverruns")]
  public static extern void set_canalStatistics_cntOverruns(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalStatistics_cntOverruns")]
  public static extern IntPtr get_canalStatistics_cntOverruns(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalStatistics_cntBusWarnings")]
  public static extern void set_canalStatistics_cntBusWarnings(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalStatistics_cntBusWarnings")]
  public static extern IntPtr get_canalStatistics_cntBusWarnings(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalStatistics_cntBusOff")]
  public static extern void set_canalStatistics_cntBusOff(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalStatistics_cntBusOff")]
  public static extern IntPtr get_canalStatistics_cntBusOff(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_new_canalStatistics")]
  public static extern IntPtr new_canalStatistics();

  [DllImport("cscanalci", EntryPoint="CSharp_delete_canalStatistics")]
  public static extern void delete_canalStatistics(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_canalStatus_channel_status")]
  public static extern void set_canalStatus_channel_status(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_canalStatus_channel_status")]
  public static extern IntPtr get_canalStatus_channel_status(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_new_canalStatus")]
  public static extern IntPtr new_canalStatus();

  [DllImport("cscanalci", EntryPoint="CSharp_delete_canalStatus")]
  public static extern void delete_canalStatus(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_devItem_id")]
  public static extern void set_devItem_id(IntPtr jarg1, int jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_devItem_id")]
  public static extern int get_devItem_id(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_devItem_regid")]
  public static extern void set_devItem_regid(IntPtr jarg1, int jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_devItem_regid")]
  public static extern int get_devItem_regid(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_devItem_name")]
  public static extern void set_devItem_name(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_devItem_name")]
  public static extern IntPtr get_devItem_name(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_devItem_path")]
  public static extern void set_devItem_path(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_devItem_path")]
  public static extern IntPtr get_devItem_path(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_devItem_deviceStr")]
  public static extern void set_devItem_deviceStr(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_devItem_deviceStr")]
  public static extern IntPtr get_devItem_deviceStr(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_devItem_flags")]
  public static extern void set_devItem_flags(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_devItem_flags")]
  public static extern IntPtr get_devItem_flags(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_devItem_inbufsize")]
  public static extern void set_devItem_inbufsize(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_devItem_inbufsize")]
  public static extern IntPtr get_devItem_inbufsize(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_devItem_outbufsize")]
  public static extern void set_devItem_outbufsize(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_devItem_outbufsize")]
  public static extern IntPtr get_devItem_outbufsize(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_devItem_filter")]
  public static extern void set_devItem_filter(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_devItem_filter")]
  public static extern IntPtr get_devItem_filter(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_set_devItem_mask")]
  public static extern void set_devItem_mask(IntPtr jarg1, IntPtr jarg2);

  [DllImport("cscanalci", EntryPoint="CSharp_get_devItem_mask")]
  public static extern IntPtr get_devItem_mask(IntPtr jarg1);

  [DllImport("cscanalci", EntryPoint="CSharp_new_devItem")]
  public static extern IntPtr new_devItem();

  [DllImport("cscanalci", EntryPoint="CSharp_delete_devItem")]
  public static extern void delete_devItem(IntPtr jarg1);
}
