/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class devItem : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal devItem(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(devItem obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~devItem() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      cscanalciPINVOKE.delete_devItem(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public int id {
    set {
      cscanalciPINVOKE.set_devItem_id(swigCPtr, value);
    } 
    get {
      return cscanalciPINVOKE.get_devItem_id(swigCPtr);
    } 
  }

  public int regid {
    set {
      cscanalciPINVOKE.set_devItem_regid(swigCPtr, value);
    } 
    get {
      return cscanalciPINVOKE.get_devItem_regid(swigCPtr);
    } 
  }

  public SWIGTYPE_p__u8 name {
    set {
      cscanalciPINVOKE.set_devItem_name(swigCPtr, SWIGTYPE_p__u8.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cscanalciPINVOKE.get_devItem_name(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p__u8(cPtr, false);
    } 
  }

  public SWIGTYPE_p__u8 path {
    set {
      cscanalciPINVOKE.set_devItem_path(swigCPtr, SWIGTYPE_p__u8.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cscanalciPINVOKE.get_devItem_path(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p__u8(cPtr, false);
    } 
  }

  public SWIGTYPE_p__u8 deviceStr {
    set {
      cscanalciPINVOKE.set_devItem_deviceStr(swigCPtr, SWIGTYPE_p__u8.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cscanalciPINVOKE.get_devItem_deviceStr(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p__u8(cPtr, false);
    } 
  }

  public SWIGTYPE_p__u32 flags {
    set {
      cscanalciPINVOKE.set_devItem_flags(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_devItem_flags(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u32 inbufsize {
    set {
      cscanalciPINVOKE.set_devItem_inbufsize(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_devItem_inbufsize(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u32 outbufsize {
    set {
      cscanalciPINVOKE.set_devItem_outbufsize(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_devItem_outbufsize(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u32 filter {
    set {
      cscanalciPINVOKE.set_devItem_filter(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_devItem_filter(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u32 mask {
    set {
      cscanalciPINVOKE.set_devItem_mask(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_devItem_mask(swigCPtr), true);
    } 
  }

  public devItem() : this(cscanalciPINVOKE.new_devItem(), true) {
  }

}
