/////////////////////////////////////////////////////////////////////////////
// Name:        configuration_symbols.h
// Purpose:     Symbols file
// Author:      Ake Hedman
// Modified by: 
// Created:     25/01/2009 16:53:46
// RCS-ID:      
// Copyright:   Copyright (C) 2007 D of Scandinavia 
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 25/01/2009 16:53:46

#define ID_CONFIGURATION_SYMBOL_0 _("Description:")
#define ID_CONFIGURATION_SYMBOL_1 _("Server URL:")
#define ID_CONFIGURATION_SYMBOL_2 _("localhost")
#define ID_CONFIGURATION_SYMBOL_3 _("Server port:")
#define ID_CONFIGURATION_SYMBOL_4 _("9598")
#define ID_CONFIGURATION_SYMBOL_5 _("Username:")
#define ID_CONFIGURATION_SYMBOL_6 _("Password:")
#define ID_CONFIGURATION_SYMBOL_7 _("Test connection")
#define ID_CONFIGURATION_SYMBOL_8 _("Host")
#define ID_CONFIGURATION_SYMBOL_9 _("Class :")
#define ID_CONFIGURATION_SYMBOL_10 _("Type :")
#define ID_CONFIGURATION_SYMBOL_11 _("Priority :")
#define ID_CONFIGURATION_SYMBOL_12 _("0 - Highest")
#define ID_CONFIGURATION_SYMBOL_13 _("1 - Even higher")
#define ID_CONFIGURATION_SYMBOL_14 _("2 - Higher")
#define ID_CONFIGURATION_SYMBOL_15 _("3 - Normal high")
#define ID_CONFIGURATION_SYMBOL_16 _("4 - Normal low")
#define ID_CONFIGURATION_SYMBOL_17 _("5 - Lower")
#define ID_CONFIGURATION_SYMBOL_18 _("6 - Even lower")
#define ID_CONFIGURATION_SYMBOL_19 _("7 - Lowest")
#define ID_CONFIGURATION_SYMBOL_20 _("0")
#define ID_CONFIGURATION_SYMBOL_21 _("GUID")
#define ID_CONFIGURATION_SYMBOL_22 _("15 - 8 :")
#define ID_CONFIGURATION_SYMBOL_23 _("7 - 0 :")
#define ID_CONFIGURATION_SYMBOL_24 _("Data :")
#define ID_CONFIGURATION_SYMBOL_25 _("You enter data for the event as a comma separated list. You can arrange the data on lines. Hexadecimal values should be preceded with '0x'.")
#define ID_CONFIGURATION_SYMBOL_26 _("Note :")
#define ID_CONFIGURATION_SYMBOL_27 _("Event")
#define ID_CONFIGURATION_SYMBOL_28 _("Configuration")
