/////////////////////////////////////////////////////////////////////////////
// Name:        vscpbutton_symbols.h
// Purpose:     Symbols file
// Author:      Ake Hedman
// Modified by: 
// Created:     25/01/2009 15:19:20
// RCS-ID:      
// Copyright:   Copyright (C) 2007 D of Scandinavia 
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 25/01/2009 15:19:20

#define ID_VSCPBUTTON_SYMBOL_0 _("VSCP Button")
