/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class canalStatistics : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal canalStatistics(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(canalStatistics obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~canalStatistics() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      cscanalciPINVOKE.delete_canalStatistics(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public SWIGTYPE_p__u32 cntReceiveFrames {
    set {
      cscanalciPINVOKE.set_canalStatistics_cntReceiveFrames(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_canalStatistics_cntReceiveFrames(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u32 cntTransmitFrames {
    set {
      cscanalciPINVOKE.set_canalStatistics_cntTransmitFrames(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_canalStatistics_cntTransmitFrames(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u32 cntReceiveData {
    set {
      cscanalciPINVOKE.set_canalStatistics_cntReceiveData(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_canalStatistics_cntReceiveData(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u32 cntTransmitData {
    set {
      cscanalciPINVOKE.set_canalStatistics_cntTransmitData(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_canalStatistics_cntTransmitData(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u32 cntOverruns {
    set {
      cscanalciPINVOKE.set_canalStatistics_cntOverruns(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_canalStatistics_cntOverruns(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u32 cntBusWarnings {
    set {
      cscanalciPINVOKE.set_canalStatistics_cntBusWarnings(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_canalStatistics_cntBusWarnings(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u32 cntBusOff {
    set {
      cscanalciPINVOKE.set_canalStatistics_cntBusOff(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_canalStatistics_cntBusOff(swigCPtr), true);
    } 
  }

  public canalStatistics() : this(cscanalciPINVOKE.new_canalStatistics(), true) {
  }

}
