/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class canalMsg : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal canalMsg(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(canalMsg obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~canalMsg() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      cscanalciPINVOKE.delete_canalMsg(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public SWIGTYPE_p__u32 flags {
    set {
      cscanalciPINVOKE.set_canalMsg_flags(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_canalMsg_flags(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u32 obid {
    set {
      cscanalciPINVOKE.set_canalMsg_obid(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_canalMsg_obid(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u32 id {
    set {
      cscanalciPINVOKE.set_canalMsg_id(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_canalMsg_id(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u8 sizeData {
    set {
      cscanalciPINVOKE.set_canalMsg_sizeData(swigCPtr, SWIGTYPE_p__u8.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u8(cscanalciPINVOKE.get_canalMsg_sizeData(swigCPtr), true);
    } 
  }

  public SWIGTYPE_p__u8 data {
    set {
      cscanalciPINVOKE.set_canalMsg_data(swigCPtr, SWIGTYPE_p__u8.getCPtr(value));
    } 
    get {
      IntPtr cPtr = cscanalciPINVOKE.get_canalMsg_data(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p__u8(cPtr, false);
    } 
  }

  public SWIGTYPE_p__u32 timestamp {
    set {
      cscanalciPINVOKE.set_canalMsg_timestamp(swigCPtr, SWIGTYPE_p__u32.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p__u32(cscanalciPINVOKE.get_canalMsg_timestamp(swigCPtr), true);
    } 
  }

  public canalMsg() : this(cscanalciPINVOKE.new_canalMsg(), true) {
  }

}
