/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class jcanalci {
  public static readonly int USE_SHM_INTERFACE = jcanalciPINVOKE.get_USE_SHM_INTERFACE();
  public static readonly int USE_DLL_INTERFACE = jcanalciPINVOKE.get_USE_DLL_INTERFACE();
}
