/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class SWIGTYPE_p__u8 {
  private IntPtr swigCPtr;

  internal SWIGTYPE_p__u8(IntPtr cPtr, bool bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p__u8() {
    swigCPtr = IntPtr.Zero;
  }

  internal static IntPtr getCPtr(SWIGTYPE_p__u8 obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }
}
