#!/bin/sh
#
# postinstall script, created by checkinstall-1.6.2
#
echo
if ! egrep "^//srv/vscp/drivers/level1 *$" /etc/ld.so.conf &> /dev/null; then
   echo "Adding "//srv/vscp/drivers/level1" to /etc/ld.so.conf"
   echo //srv/vscp/drivers/level1 >> /etc/ld.so.conf
fi
ldconfig
