#
# Makefile for canallogger 
#
# Copyright 2004 by Ake Hedman <akhe@eurosource.se>
# See COPYING for GNU Public License
#
# Linux/Solaris/FreeBSD/AIX/Other makefile
#

# Configuration
top_builddir = /usr/local/src/wxBase-2.8.0

VERSION = 0.1.0

# wxWidget
include  ${top_builddir}/src/make.env

#OPTOMIZE=-
#CXX		= g++ 
#CFLAGS		= -g -Wall -fPIC
DLFLAGS 	= -g -shared -fPIC
LIBS		= -lpthread -ldl 
#LIBS		= -ldl
#LINK_FLAGS	= 

CANALOBJS	=	
CANALHDRS	=	
PROJOBJS	=	../../../../common/dllist.o ../../../common/devicelist.o
PROJHDRS	=	../../../../common/dllist.h ../../../common/canal.h ../../../common/devicelist.h 
DLOBJS		=	lincan.o
DLHDRS		= 	lincan.h
TESTOBJ		=	test.o


# !!!!!!!
# To enable Linux support uncomment the following line (default)
# !!!!!!!
CFLAGS	+= -DLINUX

# !!!!!!!
# To enable Solaris support uncomment the following line
# This does not yet work in v2.0, anyone with Solaris want to port it??
# !!!!!!!
#CFLAGS	+= -DSOLARIS
#LIBS += -lposix4

# !!!!!!!
# To enable AIX support uncomment the following line
# !!!!!!!
#CFLAGS += -DAIX

# !!!!!!!
# To enable FreeBSD support uncomment the following line
# !!!!!!!
#CFLAGS += -DFREEBSD
  
# !!!!!!!
# If you don't use one of the above, uncomment this line and much with
# the settings in src/digitemp.c and send back your changes.
# !!!!!!!
#CFLAGS += -DOTHER
#
# build object files	
#%.o:   %.cpp
#		$(CXX) $(CFLAGS) $(OPTOMIZE) -c -o $@ $< 


#canald:		$(OBJS) $(HDRS) $(CANALOBJS) $(CANALHDR) $(PROJOBJS) $(PROJHDRS)
#		$(CC) $(OBJS) $(CANALOBJS) $(PROJOBJS) -o canald $(LIBS)	

all:	test canallogger.so

test:  $(TESTOBJ) $(HDRS) $(PROJOBJS) $(PROJHDRS)   
	$(CXX) -o test $(TESTOBJ) $(PROJOBJS) $(LIBS) $(LDLIBS) $(LINK_FLAGS)	
		
# Build the Linux DL
%.so: %.o $(DLOBJS) $(DLHDRS) $(CANALOBJS) $(CANALHDR) 
	$(CXX) $(DLFLAGS) $(OPTOMIZE) $(LIBS) -o $@ $< $(CANALOBJS) $(PROJOBJS) $(INCLUDE_DIRS)

# Clean up the object files and the sub-directory for distributions
clean:
		rm -rf *.o *.so test $(DLOBJS) $(OBJS) $(CANALOBJS) $(PROJOBJS)
		rm -f *~ $(OBJS) $(CANALOBJS) $(PROJOBJS) core *.asc
		rm -f perl/*~ rrdb/*~ canallogger-$(VERSION)-1.spec
		rm -rf canallogger-$(VERSION)

# Sign the binaries using gpg (www.gnupg.org)
# My key is available from www.vscp.org
sign:
		gpg -ba canallogger


# Install canald into /usr/local/bin
install:	canallogger
		install -b -o root -g bin canallogger /usr/local/bin

# Build the archive of everything
archive:	canald clean sign
		cd .. ; tar cvzf delivery/canallogger-$(VERSION).tar.gz * --exclude *.o --exclude *.exe 

# Build the source distribution

source:		archive

dist:		archive

# Build RedHat binary and source RPMs
rpm:	dist
	su -c "cp ../deliver/canallogger-$(VERSION).tar.gz /usr/src/redhat/SOURCES"
	rm -f canallogger-$(VERSION)-1.spec
	ln -s canallogger.spec canallogger-$(VERSION)-1.spec
	su -c "rpm -ba -vv canallogger-$(VERSION)-1.spec"

