#!/bin/bash

reading=`/usr/local/bin/digitemp -s /dev/ttyS0 -a -q`

#echo $reading

temp=`echo $reading | gawk '{print $7}'`
echo $(($temp << 8))

temp=`echo $reading | gawk '{print $16}'`
echo $temp

temp=`echo $reading | gawk '{print $25}'`
echo $temp

temp=`echo $reading | gawk '{print $34}'`
echo $temp

