name: Build VSCP library on Linux

on:
  push:
    branches: [ master, main, development ]
  pull_request:
    branches: [ master, main, development ]

permissions:
  contents: read

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Update package lists
      run: sudo apt-get update

    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          libssl-dev \
          libexpat-dev \
          libcurl4-openssl-dev \
          libmosquitto-dev

    - name: Create build directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel $(nproc)