name: Build VSCP library on Windows

on:
  push:
    branches: [ master, main, development ]
  pull_request:
    branches: [ master, main, development ]

env:
  BUILD_TYPE: Release
  VCPKG_DEFAULT_TRIPLET: x64-windows

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Clone vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install dependencies via vcpkg
      run: .\vcpkg\vcpkg install --triplet x64-windows
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} `
          -DVCPKG_TARGET_TRIPLET=x64-windows `
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
